import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as THREE from 'three';
import {OBB} from 'three/examples/jsm/math/OBB.js';
import {checks,provenance} from '../src/content.js';
import {newSession,commit,submitResponse,beginRetry,exposeActivity,restartSession} from '../src/model.js';
import {createConstruction,currentStep,finishStep,beginRedo,reasoningReady,acknowledgeStep} from '../src/construction.js';
import {challengeStatus,teacherReport} from '../src/assessment.js';
const house=JSON.parse(fs.readFileSync('data/house.json')),plan=createConstruction(house,checks),manifest={id:'synthetic-identified-build',sourceRevision:'synthetic-sha',builtAt:'2026-10-01T00:00:00Z',fingerprint:'synthetic'};
const concept=(s,c)=>{if(c?.question)submitResponse(s,c.id,c.answer,c.answer);if(c?.explanation)submitResponse(s,c.id+':explanation','Synthetic explanation for teacher review.',null)};
function solve(s){const st=currentStep(s,plan),c=checks.find(c=>c.id===st.exercise);s.phase='selecting';concept(s,c);if(st.length!==null){s.selected=st.length;commit(s,st.length,st.id);s.phase='inspecting';assert.ok(acknowledgeStep(s,plan,checks)?.keep)}finishStep(s,plan);s.phase=s.step===plan.steps.length?'complete':'selecting'}
test('Twenty-five exercise IDs appear once, with seven additional house measurements',()=>{assert.equal(plan.steps.length,32);assert.deepEqual(plan.projects.map(p=>p.id),['chair','plane','house']);assert.equal(new Set(plan.steps.filter(s=>s.exercise).map(s=>s.exercise)).size,25);for(const c of checks)assert.equal(plan.steps.filter(s=>s.exercise===c.id).length,1);for(const p of plan.projects){const lengths=plan.steps.filter(s=>s.project===p.id&&s.length!==null).map(s=>s.length);assert.equal(new Set(lengths).size,lengths.length,'Only one measured family per model length')}assert.equal(plan.steps.find(s=>s.exercise==='MT-C29').placements.length,3);assert.equal(plan.steps.find(s=>s.exercise==='MT-C30').placements.length,5)});
test('Every measured placement has its exact length and the original 17 frame endpoints are unchanged',()=>{for(const step of plan.steps)for(const p of step.placements){assert.ok(Math.abs(Math.hypot(...p.to.map((v,i)=>v-p.from[i]))-step.length)<1e-10,step.id);assert.ok(p.from.every(Number.isFinite)&&p.to.every(Number.isFinite))}const frame=plan.steps.flatMap(s=>s.placements.filter(p=>p.role==='frame').map(({from,to})=>({from,to})));assert.deepEqual(frame,house.families.flatMap(f=>f.placements));assert.equal(frame.length,17)});
test('Each model forms a connected wooden structure using the actual constant-profile oriented boxes',()=>{
 for(const project of plan.projects){const boxes=plan.steps.filter(s=>s.project===project.id).flatMap(s=>s.placements.map(p=>{const a=new THREE.Vector3(...p.from).multiplyScalar(1/8),b=new THREE.Vector3(...p.to).multiplyScalar(1/8),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(1,0,0),b.clone().sub(a).normalize());q.multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),p.roll??0));return {step:s.id,box:new OBB(a.clone().add(b).multiplyScalar(.5),new THREE.Vector3(s.length/16,.11,.315),new THREE.Matrix3().setFromMatrix4(new THREE.Matrix4().makeRotationFromQuaternion(q)))}}));const seen=new Set([0]);let added=true;while(added){added=false;for(let i=0;i<boxes.length;i++)if(!seen.has(i)&&[...seen].some(j=>boxes[i].box.intersectsOBB(boxes[j].box,1e-8))){seen.add(i);added=true}}assert.equal(seen.size,boxes.length,project.id+' disconnected: '+boxes.filter((_,i)=>!seen.has(i)).map(b=>b.step).join(','))}
});
test('A correct cut stays held through reasoning repair, with one cut and immutable original responses',()=>{const s=newSession('challenge');s.activity='build';s.step=plan.steps.findIndex(st=>st.id==='MT-C03');const st=currentStep(s,plan),c=checks.find(c=>c.id===st.id);submitResponse(s,c.id,c.options.find(v=>v!==c.answer),c.answer);submitResponse(s,c.id+':explanation','Original reasoning',null);const first=JSON.stringify(s.responses);s.selected=st.length;commit(s,st.length,st.id);s.phase='inspecting';assert.equal(acknowledgeStep(s,plan,checks),null);assert.equal(s.parts.length,0);exposeActivity(s,c.id);beginRetry(s,c.id);concept(s,c);assert.equal(reasoningReady(s,c),true);assert.equal(s.attempts.length,1);assert.equal(JSON.stringify(s.responses.slice(0,2)),first);assert.ok(acknowledgeStep(s,plan,checks).keep);assert.equal(s.builtSteps.length,0,'Placement animation must finish before step completion');finishStep(s,plan);assert.equal(s.parts.length,st.placements.length)});
test('All objectives and all placed models gate the report; redo and restart preserve evidence without duplicate awards',()=>{let s=newSession('challenge');s.activity='build';for(let i=0;i<plan.steps.length-1;i++)solve(s);assert.equal(challengeStatus(s,checks,plan).complete,false);assert.throws(()=>teacherReport(s,checks,plan,manifest,provenance));solve(s);assert.equal(challengeStatus(s,checks,plan).complete,true);const count=s.parts.length,original=JSON.stringify(s.attempts[0]);assert.ok(teacherReport(s,checks,plan,manifest,provenance).includes('Original House Frame: 17/17'));assert.equal(beginRedo(s,plan.steps.length-1,plan),true);beginRetry(s,currentStep(s,plan).id);assert.equal(challengeStatus(s,checks,plan).complete,false);solve(s);assert.equal(s.parts.length,count);assert.equal(challengeStatus(s,checks,plan).complete,true);assert.equal(JSON.stringify(s.attempts[0]),original);s=restartSession(s);assert.equal(s.parts.length,0);assert.equal(s.builtSteps.length,0);assert.equal(challengeStatus(s,checks,plan).complete,false);assert.equal(JSON.stringify(s.attempts[0]),original)});

// Retired questions never become automatic successes; their old evidence survives.
test('Retired fit questions are excluded while every additional house measurement still gates completion',()=>{
 const s=newSession('challenge');s.activity='build';submitResponse(s,'MT-C05','Too Short','Too Short');const retired=JSON.stringify(s.responses[0]);
 for(let i=0;i<plan.steps.length;i++)solve(s);const result=challengeStatus(s,checks,plan);assert.equal(result.total,25);assert.equal(result.correctCount,25);assert.equal(result.complete,true);assert.equal(s.parts.length,104);assert.equal(plan.steps.filter(st=>!st.exercise).length,7);assert.ok(result.exercises.every(e=>!provenance.retiredChallengeIds.includes(e.id)));
 const report=teacherReport(s,checks,plan,manifest,provenance);assert.match(report,/Automatic Components Complete: 25\/25/);assert.match(report,/Additional House Construction Measurements/);assert.ok(report.includes('"id": "MT-C05"'));assert.equal(JSON.stringify(s.responses[0]),retired);
 for(const st of plan.steps.filter(st=>!st.exercise)){const missing={...s,builtSteps:s.builtSteps.filter(id=>id!==st.id)};assert.equal(challengeStatus(missing,checks,plan).complete,false,st.id);assert.throws(()=>teacherReport(missing,checks,plan,manifest,provenance));}
 const noChoice=newSession('challenge');noChoice.activity='build';noChoice.step=plan.steps.findIndex(st=>st.id==='house:roof-boards');const st=currentStep(noChoice,plan);noChoice.selected=st.length-1;commit(noChoice,st.length,st.id);noChoice.phase='inspecting';assert.equal(acknowledgeStep(noChoice,plan,checks).keep,false);assert.equal(noChoice.responses.length,0);assert.equal(noChoice.parts.length,0);assert.equal(currentStep(noChoice,plan).id,st.id);solve(noChoice);assert.equal(noChoice.parts.length,8);assert.equal(noChoice.responses.length,0);
});
