import test from 'node:test';
import assert from 'node:assert/strict';
import {lessons,checks,provenance} from '../src/content.js';
import {newSession,commit,submitResponse,exposeActivity,restartSession,hasExposure} from '../src/model.js';
test('Five indexed lessons and six seed checks preserve exact targets and source provenance',()=>{assert.equal(lessons.length,5);assert.equal(checks.length,30);assert.equal(new Set([...lessons,...checks].map(x=>x.id)).size,35);assert.deepEqual(checks.slice(0,6).map(x=>x.target),[6,7,12,19,20,null]);assert.equal(provenance.audit,'1713a3bd537035f2ce09dfc7fe05ce6bf6b70cc3');for(const l of lessons){assert.ok(l.pages&&l.goals.length&&l.objective&&l.demo.length&&l.practice)}});
test('Typed text is retained for teacher review and never automatically passed',()=>{const s=newSession('challenge');assert.equal(submitResponse(s,'MT-C03:explanation','anything',null),true);assert.equal(s.responses[0].correct,null);assert.equal(s.responses[0].review,'Teacher Review');assert.equal(submitResponse(s,'MT-C03:explanation','changed answer',null),false);assert.equal(s.responses[0].answer,'anything')});
test('A wrong concept answer is distinguishable; hints and exposure mark support',()=>{const s=newSession('challenge');submitResponse(s,'MT-C06','The Wood Color','The Unit');assert.equal(s.responses[0].correct,false);s.hint=true;s.selected=7;commit(s,7,'MT-C02');assert.equal(s.attempts[0].assisted,true);s.phase='selecting';s.hint=false;s.exposed.push('MT-C04');commit(s,19,'MT-C04');assert.equal(s.attempts[1].assisted,true)});
test('Activity support reaches every component and does not rewrite original independent records',()=>{const s=newSession('challenge');submitResponse(s,'MT-C03','Yes','Yes');const original=JSON.stringify(s.responses[0]);exposeActivity(s,'MT-C03');submitResponse(s,'MT-C03:explanation','Same endpoint',null);assert.equal(s.responses[1].assisted,true);assert.equal(JSON.stringify(s.responses[0]),original);assert.equal(submitResponse(s,'MT-C03','No','Yes'),false);assert.equal(hasExposure(s,'MT-C03:explanation'),true)});
test('Restart retains exposure and immutable first responses while clearing construction',()=>{let s=newSession('challenge');s.selected=18;commit(s,20,'house:uprights');const first=JSON.stringify(s.attempts[0]);exposeActivity(s,'house:uprights');exposeActivity(s,'MT-C03:explanation');submitResponse(s,'MT-C03','Yes','Yes');s=restartSession(s);s.selected=20;commit(s,20,'house:uprights');assert.equal(JSON.stringify(s.attempts[0]),first);assert.equal(s.attempts[1].assisted,true);assert.equal(s.responses.length,1);assert.equal(hasExposure(s,'MT-C03'),true);assert.equal(s.parts.length,0)});
