const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const report=JSON.parse(fs.readFileSync('latest-review.json')),root=report.directory,evidence='test-results/'+report.id;fs.mkdirSync(evidence,{recursive:true});
 const server=http.createServer((req,res)=>{let p=path.join(root,new URL(req.url,'http://localhost').pathname);if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)){res.writeHead(404).end();return}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.html')?'text/html':'application/json');fs.createReadStream(p).pipe(res)});
 await new Promise(r=>server.listen(18446,'127.0.0.1',r));let browser;
 try{
  browser=await chromium.launch({executablePath:process.env.MT_BROWSER||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const fresh=async()=>{await page.goto('http://127.0.0.1:18446');await page.waitForFunction(()=>window.mtReview?.chooseCheck);await page.check('#reduced')};
  const snap=()=>page.evaluate(()=>mtReview.snapshot());
  const answer=async()=>{await page.locator('input[name="answer"]').first().check();await page.fill('#explanation','The same endpoint on one inch.');await page.locator('#response-form button[type="submit"]').click()};
  await fresh();await page.evaluate(()=>mtReview.chooseCheck(2));assert.equal((await page.locator('#target').textContent()).trim(),'6/8 in');assert.match(await page.locator('#order-note').textContent(),/Mark 6\/8 inch/);assert.equal((await snap()).responses.length,0);assert.equal((await snap()).attempts.length,0);assert.equal((await snap()).exposed.includes('MT-C03'),false);assert.equal(await page.locator('#result').isVisible(),false);await page.screenshot({path:evidence+'/c03-before-response.png'});
  await page.evaluate(()=>{mtReview.select(12);mtReview.cut()});await answer();let s=await snap();assert.equal(s.attempts[0].assisted,false);assert.equal(s.responses[0].assisted,false);assert.equal(s.responses[1].assisted,false);assert.match(await page.locator('#needed').textContent(),/3\/4/);const first=JSON.stringify(s.responses);await page.evaluate(()=>{mtReview.acknowledge();mtReview.mode('learn');mtReview.chooseLesson(2);mtReview.mode('challenge');mtReview.restart()});assert.equal(JSON.stringify((await snap()).responses),first);
  await fresh();await page.evaluate(()=>{mtReview.mode('learn');mtReview.chooseLesson(2)});assert.match(await page.locator('#guidance').textContent(),/Three quarters and six eighths/);assert.equal((await snap()).attempts.length,0);await page.evaluate(()=>{mtReview.mode('challenge');mtReview.chooseCheck(2);mtReview.select(12);mtReview.cut()});await answer();s=await snap();assert.equal(s.attempts[0].assisted,true);for(const r of s.responses.filter(r=>r.id.startsWith('MT-C03')))assert.equal(r.assisted,true);assert.equal(s.responses.length,2);
  await fresh();await page.evaluate(()=>mtReview.chooseCheck(2));await page.click('#hint');await page.click('#close-panel');await page.evaluate(()=>{mtReview.chooseCheck(1);mtReview.chooseCheck(2);mtReview.select(12);mtReview.cut()});await answer();s=await snap();assert.equal(s.hint,false);assert.equal(s.attempts[0].assisted,true);assert.equal(s.responses.find(r=>r.id==='MT-C03:explanation').assisted,true);
  await fresh();await page.evaluate(()=>{mtReview.select(18);mtReview.cut()});s=await snap();assert.equal(s.attempts[0].assisted,false);assert.equal(s.exposed.includes(s.pending.context),true);const original=JSON.stringify(s.attempts[0]);await page.evaluate(()=>{mtReview.restart();mtReview.select(20);mtReview.cut()});s=await snap();assert.equal(s.attempts.length,2);assert.equal(s.attempts[1].assisted,true);assert.equal(JSON.stringify(s.attempts[0]),original);
  assert.deepEqual(errors,[]);assert.equal(await page.locator('#build-id').textContent(),report.id);const checks=['C03 Authored 6/8 Target Before Any Response','Normalized Feedback Only After Cut','Guidance-Only Exposure Across Modes','Hint Exposure Survives Navigation','Objective and Explanation Inherit Exposure','Original Independent Records Unchanged','House Inspection Exposure Survives Restart'];fs.writeFileSync(evidence+'/assessment-verification.json',JSON.stringify({id:report.id,checks,errors},null,2));console.log(JSON.stringify({id:report.id,checks,errors}));
 }finally{await browser?.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exitCode=1});
