const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
  const report=JSON.parse(fs.readFileSync('latest-review.json')),root=report.directory;
  const evidence='test-results/'+report.id;fs.mkdirSync(evidence,{recursive:true});
  const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file)){res.writeHead(404).end();return}res.setHeader('Content-Type',file.endsWith('.js')||file.endsWith('.mjs')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':file.endsWith('.html')?'text/html':'application/octet-stream');fs.createReadStream(file).pipe(res)});
  await new Promise(r=>server.listen(18444,'127.0.0.1',r));
  const browser=await chromium.launch({executablePath:process.env.MT_BROWSER||(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':undefined),headless:true,args:['--enable-unsafe-swiftshader']});
  const page=await browser.newPage({viewport:{width:1366,height:768}});const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',route=>{if(!route.request().url().startsWith('http://127.0.0.1:18444')){external.push(route.request().url());return route.abort()}return route.continue()});
  await page.goto('http://127.0.0.1:18444');await page.waitForFunction(()=>window.mtReview);await page.screenshot({path:evidence+'/review-workshop.png'});
  const snap=()=>page.evaluate(()=>window.mtReview.snapshot());
  await page.locator('#ruler').focus();await page.keyboard.press('ArrowRight');assert.equal((await snap()).selected,17);
  await page.evaluate(()=>{mtReview.select(18);mtReview.cut()});await page.waitForFunction(()=>mtReview.snapshot().phase==='inspecting',{timeout:15000});assert.equal((await snap()).pending.correct,false);assert.equal((await snap()).pending.actual,18);await page.screenshot({path:evidence+'/review-short.png'});
  await page.waitForTimeout(500);assert.equal((await snap()).phase,'inspecting');await page.evaluate(()=>mtReview.mode('free'));await page.evaluate(()=>mtReview.mode('challenge'));assert.equal((await snap()).phase,'inspecting');
  await page.check('#reduced');await page.evaluate(()=>{mtReview.acknowledge();mtReview.select(22);mtReview.cut()});assert.equal((await snap()).pending.correct,false);assert.equal((await snap()).parts.length,0);await page.screenshot({path:evidence+'/review-long.png'});
  await page.evaluate(()=>{mtReview.acknowledge();for(const length of [20,32,16]){mtReview.select(length);mtReview.cut();mtReview.cut();mtReview.acknowledge();mtReview.acknowledge()}});const completed=await snap();assert.equal(completed.parts.length,17);assert.equal(completed.completed.length,3);assert.equal(completed.attempts.length,5);assert.equal(completed.phase,'complete');assert.equal(completed.attempts[0].assisted,false);assert.equal(completed.attempts[2].retry,true);assert.equal(completed.attempts[2].assisted,true);
  const geometry=await page.evaluate(()=>mtReview.geometry());for(const part of geometry){assert.equal(part.meshLength,part.length/8);assert.deepEqual(part.scale,[1,1,1])}
  await page.screenshot({path:evidence+'/review-house.png'});const cam=await page.evaluate(()=>mtReview.camera());await page.click('#orbit-left');assert.notDeepEqual(await page.evaluate(()=>mtReview.camera()),cam);
  await page.evaluate(()=>{mtReview.mode('free');mtReview.select(7);mtReview.cut();mtReview.acknowledge();mtReview.select(26);mtReview.cut();mtReview.acknowledge();mtReview.duplicate()});assert.equal((await snap()).parts.length,3);assert.equal((await snap()).attempts.length,2);await page.screenshot({path:evidence+'/review-free.png'});
  await page.evaluate(()=>mtReview.mode('challenge'));assert.equal((await snap()).parts.length,17);await page.evaluate(()=>mtReview.mode('free'));assert.equal((await snap()).parts.length,3);
  await page.uncheck('#reduced');await page.evaluate(()=>{mtReview.select(19);mtReview.cut();mtReview.mode('learn')});await page.evaluate(()=>mtReview.mode('free'));assert.equal((await snap()).phase,'inspecting');assert.equal((await snap()).attempts.length,3);
  await page.check('#reduced');await page.evaluate(()=>mtReview.acknowledge());
  for(const viewport of [{width:1366,height:768},{width:1024,height:768}]){await page.setViewportSize(viewport);for(const n of [7,19,47]){const b=await page.locator('#ruler').boundingBox();await page.mouse.click(b.x+24+n/48*(b.width-48),b.y+30);assert.equal((await snap()).selected,n);const positions=await page.locator('#ruler').evaluate(svg=>{const marker=svg.querySelector('circle'),p=svg.createSVGPoint();p.x=Number(marker.getAttribute('cx'));p.y=7;const q=p.matrixTransform(svg.getScreenCTM());return {x:q.x}});assert.ok(Math.abs(positions.x-(b.x+24+n/48*(b.width-48)))<1)}}
  await page.click('#magnify');await page.locator('#ruler-scroll').evaluate(e=>e.scrollLeft=240);let rb=await page.locator('#ruler').boundingBox();await page.mouse.click(rb.x+24+19/48*(rb.width-48),rb.y+30);assert.equal((await snap()).selected,19);await page.locator('#ruler').focus();for(const key of ['End','ArrowLeft','Home','ArrowRight']){await page.keyboard.press(key);const visible=await page.locator('#ruler').evaluate(svg=>{const sc=document.getElementById('ruler-scroll'),b=sc.getBoundingClientRect(),p=svg.createSVGPoint();p.x=Number(svg.querySelector('circle').getAttribute('cx'));p.y=7;const q=p.matrixTransform(svg.getScreenCTM());return q.x>=b.left&&q.x<=b.right});assert.equal(visible,true,'Magnified keyboard selection stays visible');}await page.click('#magnify');await page.setViewportSize({width:1366,height:768});
  await page.evaluate(()=>{mtReview.restart();for(const n of [7,26,48,16,20,12,32]){mtReview.select(n);mtReview.cut();mtReview.acknowledge()}});const comparison=await page.evaluate(()=>mtReview.geometry());assert.equal(comparison.length,7);for(let i=0;i<comparison.length;i++){const p=comparison[i];assert.ok(Math.abs(p.position[0]-p.meshLength/2-.3)<1e-9);for(let j=0;j<i;j++)assert.ok(Math.abs(p.position[2]-comparison[j].position[2])>p.profileWidth)}await page.screenshot({path:evidence+'/seven-piece-comparison.png'});
  if(process.argv.includes('--learning')){
    await page.waitForFunction(()=>mtReview.content);
    await page.evaluate(()=>mtReview.mode('learn'));
    for(let i=0;i<5;i++){await page.evaluate(i=>{mtReview.chooseLesson(i);mtReview.select(mtReview.content().lessons[i].guided);mtReview.cut()},i);assert.equal((await snap()).phase,'inspecting');assert.equal((await snap()).pending.correct,true);await page.evaluate(()=>mtReview.acknowledge())}
    await page.evaluate(()=>mtReview.chooseLesson(2));await page.screenshot({path:evidence+'/review-learn.png'});await page.click('#practice');assert.equal(await page.locator('#readout').isVisible(),false);await page.click('#demo');await page.evaluate(()=>mtReview.mode('challenge'));await page.evaluate(()=>mtReview.mode('learn'));assert.equal((await snap()).demonstrating,false);
    await page.evaluate(()=>mtReview.mode('challenge'));
    for(const [i,length] of [[0,6],[1,7],[2,12],[3,19]]){await page.evaluate(({i,length})=>{mtReview.chooseCheck(i);mtReview.select(length);mtReview.cut()},{i,length});if(i===0||i===2){assert.equal((await snap()).phase,'selecting');assert.equal(await page.locator('#result').isVisible(),false);await page.locator('input[name="answer"]').first().check();if(i===2)await page.fill('#explanation','Both end at the same place on the same inch.');await page.locator('#response-form button[type="submit"]').click()}assert.equal((await snap()).phase,'inspecting');assert.equal((await snap()).pending.correct,true);await page.evaluate(()=>mtReview.acknowledge())}
    await page.evaluate(()=>mtReview.chooseCheck(4));assert.equal((await snap()).responses.some(r=>r.id==='MT-C05'),false);await page.locator('input[name="answer"]').first().check();await page.fill('#explanation','It is shorter and leaves a gap.');await page.locator('#response-form button[type="submit"]').click();assert.equal((await snap()).responses.find(r=>r.id==='MT-C05:explanation').correct,null);await page.screenshot({path:evidence+'/review-concept.png'});await page.click('#close-panel');
    await page.evaluate(()=>mtReview.chooseCheck(5));await page.locator('input[name="answer"]').nth(1).check();await page.locator('#response-form button[type="submit"]').click();assert.equal((await snap()).responses.find(r=>r.id==='MT-C06').correct,false);await page.click('#close-panel');
    await page.click('#curriculum');await page.getByText('Graduation',{exact:true}).hover();await page.getByText('Interval',{exact:true}).hover();assert.equal(await page.locator('details.vocab[open]').count(),2);await page.screenshot({path:evidence+'/review-vocabulary.png'});await page.click('#close-panel');
    const learning=await page.evaluate(()=>mtReview.allSessions());assert.equal(learning.challenge.parts.filter(p=>p.family).length,17);assert.equal(learning.challenge.responses.find(r=>r.id==='MT-C03:explanation').review,'Teacher Review');fs.writeFileSync(evidence+'/learning-verification.json',JSON.stringify({id:report.id,learning},null,2));
    await page.setViewportSize({width:1024,height:768});await page.evaluate(()=>mtReview.mode('learn'));await page.screenshot({path:evidence+'/review-compact.png'});
  }
  assert.equal(await page.locator('#build-id').textContent(),report.id);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  fs.writeFileSync(evidence+'/review-verification.json',JSON.stringify({id:report.id,completed,geometry,errors,external,checks:['Real WebGL Render','Full Cut and Camera Travel','Held Short/Long Inspection','17 Pieces in 3 Families','Duplicate Commitment Protection','Free Play Retention and Duplication','Mode-Switch Mid-Cut Preservation','Camera Orbit','Keyboard Ruler','Offline Runtime','Visible Build Identity']},null,2));
  console.log(JSON.stringify({id:report.id,parts:completed.parts.length,errors,external}));await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
