const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const report=JSON.parse(fs.readFileSync('latest-review.json')),root=report.directory,evidence=path.join('test-results',report.id),port=18454,base=`http://127.0.0.1:${port}`;fs.mkdirSync(evidence,{recursive:true});
 const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+new URL(req.url,base).pathname);if(!file.startsWith(root+path.sep)&&file!==root){res.writeHead(403).end();return}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file)){res.writeHead(404).end();return}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/json');fs.createReadStream(file).pipe(res)});
 await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve)});let browser;
 try{
  browser=await chromium.launch({executablePath:process.env.MT_BROWSER||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-unsafe-swiftshader']});
  const page=await browser.newPage({viewport:{width:1366,height:768},acceptDownloads:true}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning'&&m.text().startsWith('Learning module:'))errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)requests.push(r.url())});await page.route('**/*',route=>{if(!route.request().url().startsWith(base+'/')){requests.push(route.request().url());return route.abort()}return route.continue()});
  await page.goto(base);await page.waitForFunction(()=>window.mtReview?.challengeStatus);await page.check('#reduced');assert.equal(await page.locator('#build-id').textContent(),report.id);
  const snap=()=>page.evaluate(()=>mtReview.snapshot()),status=()=>page.evaluate(()=>mtReview.challengeStatus()),bank=await page.evaluate(()=>mtReview.content().checks);
  const answer=async(c,wrong=false)=>{const option=wrong?c.options.find(o=>o!==c.answer):c.answer;await page.getByRole('radio',{name:option,exact:true}).check();if(c.explanation)await page.fill('#explanation',`Synthetic teacher-review example for ${c.id}: I compared the measured spans and starting reference.`);await page.locator('#response-form button[type="submit"]').click()};
  const solve=async(i)=>{const c=bank[i];await page.evaluate(i=>mtReview.chooseCheck(i),i);if(c.targetLabel)assert.equal((await page.locator('#target').textContent()).trim(),c.targetLabel+' in');if(c.kind==='cut'){await page.evaluate(n=>{mtReview.select(n);mtReview.cut()},c.target);if(c.question)await answer(c);assert.equal((await snap()).phase,'inspecting');await page.evaluate(()=>mtReview.acknowledge())}else{await answer(c);await page.click('#close-panel')}assert.equal((await status()).exercises[i].complete,true)};
  await page.click('#checks');assert.equal(await page.locator('#completion-report').isDisabled(),true);await page.click('#close-panel');
  await page.evaluate(()=>{for(const n of [20,32,16]){mtReview.select(n);mtReview.cut();mtReview.acknowledge()}});assert.equal((await status()).houseComplete,true);assert.equal((await status()).complete,false);assert.match(await page.locator('#complete').textContent(),/House Assembled/);assert.doesNotMatch(await page.locator('#complete').textContent(),/^Challenge Complete/);
  // Wrong objective, an explicit retry, and a Learn visit retain original observations.
  await page.evaluate(()=>mtReview.chooseCheck(5));await answer(bank[5],true);const firstObjective=JSON.stringify((await snap()).responses[0]);assert.equal((await status()).exercises[5].complete,false);await page.click('#retry-check');await answer(bank[5]);assert.equal((await status()).exercises[5].complete,true);assert.equal((await status()).exercises[5].firstIndependentCorrect,false);await page.click('#close-panel');
  await page.evaluate(()=>{mtReview.chooseCheck(1);mtReview.select(8);mtReview.cut()});const firstCut=JSON.stringify((await snap()).attempts.at(-1));assert.equal((await status()).exercises[1].complete,false);await page.evaluate(()=>{mtReview.acknowledge();mtReview.select(7);mtReview.cut()});assert.equal((await status()).exercises[1].complete,false);assert.equal((await snap()).attempts.at(-1).assisted,true);await page.evaluate(()=>mtReview.acknowledge());assert.equal((await status()).exercises[1].complete,true);
  await page.evaluate(()=>{mtReview.mode('learn');mtReview.chooseLesson(2);mtReview.mode('challenge')});let s=await snap();assert.equal(JSON.stringify(s.responses[0]),firstObjective);assert.equal(JSON.stringify(s.attempts.find(a=>a.context==='MT-C02')),firstCut);assert.equal((await status()).correctCount,2);
  // Correct cut plus wrong fit judgment must stay incomplete; both can be retried.
  await page.evaluate(()=>{mtReview.chooseCheck(22);mtReview.select(11);mtReview.cut()});await answer(bank[22],true);assert.equal((await snap()).phase,'inspecting');await page.evaluate(()=>mtReview.acknowledge());assert.equal((await status()).exercises[22].complete,false);await page.click('#retry-exercise');await page.evaluate(()=>{mtReview.select(11);mtReview.cut()});await answer(bank[22]);await page.evaluate(()=>mtReview.acknowledge());assert.equal((await status()).exercises[22].complete,true);assert.equal((await status()).exercises[22].firstIndependentCorrect,false);
  for(let i=0;i<29;i++)if(!(await status()).exercises[i].complete)await solve(i);
  assert.equal((await status()).correctCount,29);await page.click('#checks');assert.equal(await page.locator('#completion-report').isDisabled(),true);await page.screenshot({path:path.join(evidence,'challenge-progress.png')});await page.click('#close-panel');
  await solve(29);let final=await status();assert.equal(final.correctCount,30);assert.equal(final.complete,true);assert.match(await page.locator('#complete').textContent(),/^Challenge Complete/);await page.screenshot({path:path.join(evidence,'challenge-complete.png')});
  const geometry=await page.evaluate(()=>mtReview.geometry());for(const part of geometry){assert.equal(part.meshLength,part.length/8);assert.deepEqual(part.scale,[1,1,1])}for(const c of bank.slice(-2)){const pieces=geometry.filter(p=>p.context===c.id);assert.equal(pieces.length,c.copies);assert.equal(pieces.filter(p=>p.original).length,1)}
  await page.click('#checks');assert.equal(await page.locator('#completion-report').isEnabled(),true);const downloadPromise=page.waitForEvent('download');await page.click('#completion-report');const download=await downloadPromise,downloadPath=path.join(evidence,download.suggestedFilename());assert.equal(download.suggestedFilename(),report.id+'_Challenge-Report.txt');await download.saveAs(downloadPath);const text=fs.readFileSync(downloadPath,'utf8');assert.ok(text.includes(report.id)&&text.includes(report.sourceRevision));for(const c of bank)assert.ok(text.includes(c.id));assert.match(text,/Do Not Count as Independent First-Attempt Success/);assert.match(text,/Incorrect/);assert.match(text,/Retry/);assert.match(text,/Assisted \/ Previously Exposed/);assert.match(text,/Teacher Review/);
  await page.click('#close-panel');const before=JSON.stringify((await snap()).responses);await page.evaluate(()=>mtReview.restart());assert.equal((await status()).correctCount,30);assert.equal((await status()).complete,false);assert.equal(JSON.stringify((await snap()).responses),before);await page.click('#checks');assert.equal(await page.locator('#completion-report').isDisabled(),true);await page.click('#close-panel');await page.evaluate(()=>{for(const n of [20,32,16]){mtReview.select(n);mtReview.cut();mtReview.acknowledge()}});assert.equal((await status()).complete,true);
  await page.setViewportSize({width:1024,height:768});await page.click('#checks');assert.equal(await page.locator('#completion-report').isEnabled(),true);assert.equal(await page.locator('[data-check]').count(),30);await page.locator('[data-check="29"]').scrollIntoViewIfNeeded();assert.equal(await page.locator('[data-check="29"]').isVisible(),true);await page.click('#close-panel');
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);const result={id:report.id,sourceRevision:report.sourceRevision,exerciseCount:bank.length,checks:['All 30 Actual Exercise Flows','Authored Equivalence Labels Before Commitment','House Alone Does Not Complete Challenge','Wrong Choice and Cut Retries Preserve Originals','Correct Cut Cannot Mask Wrong Fit Judgment','Learn Visit Preserves Progress and Support','All Automatic Components Required','Explanations Remain Teacher-Reviewed','Equal-Copy Tasks Keep Exact Original Plus N-1','Actual Offline Teacher Report Download','Restart Keeps Exercise Evidence but Resets Construction','1024x768 and 1366x768 Progress Access'],finalResults:final.exercises.map(e=>({id:e.id,complete:e.complete,firstIndependentCorrect:e.firstIndependentCorrect})),reportFile:download.suggestedFilename(),syntheticStudentData:true,errors,requests};fs.writeFileSync(path.join(evidence,'challenge-verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await browser?.close();await new Promise(resolve=>server.close(resolve))}
})().catch(e=>{console.error(e);process.exitCode=1});
