const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const report=JSON.parse(fs.readFileSync('latest-review.json')),root=report.directory,evidence=path.join('test-results',report.id),port=18454,base=`http://127.0.0.1:${port}`;fs.mkdirSync(evidence,{recursive:true});
 const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+new URL(req.url,base).pathname);if(!file.startsWith(root+path.sep)&&file!==root){res.writeHead(403).end();return}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file)){res.writeHead(404).end();return}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/json');fs.createReadStream(file).pipe(res)});
 await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve)});let browser;
 try{
  browser=await chromium.launch({executablePath:process.env.MT_BROWSER||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1366,height:768},acceptDownloads:true}),errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning'&&m.text().startsWith('Learning module:'))errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)requests.push(r.url())});await page.route('**/*',route=>{if(!route.request().url().startsWith(base+'/')){requests.push(route.request().url());return route.abort()}return route.continue()});
  await page.goto(base);await page.waitForFunction(()=>window.mtReview?.plan);await page.check('#reduced');assert.equal(await page.locator('#build-id').textContent(),report.id);
  const snap=()=>page.evaluate(()=>mtReview.snapshot()),status=()=>page.evaluate(()=>mtReview.challengeStatus()),plan=await page.evaluate(()=>mtReview.plan()),bank=await page.evaluate(()=>mtReview.content().checks);
  const answer=async(c,wrong=false)=>{await page.getByRole('radio',{name:wrong?c.options.find(o=>o!==c.answer):c.answer,exact:true}).check();if(c.explanation)await page.fill('#explanation',`Synthetic reasoning for ${c.id}: I compared the measured spans.`);await page.locator('#response-form button[type="submit"]').click()};
  assert.equal(plan.steps.length,32);assert.equal((await snap()).step,0);assert.equal(await page.locator('#target').isVisible(),false);assert.equal((await snap()).parts.length,0);
  await page.click('#checks');assert.equal(await page.locator('[data-check]').count(),0);assert.equal(await page.locator('[data-review]').count(),0);assert.equal(await page.locator('#completion-report').isDisabled(),true);await page.click('#continue-build');
  // Unit-order reasoning is held for confirmation, with no guessed automatic pass.
  await page.click('#plan-order');await answer(bank[5],true);const originalChoice=JSON.stringify((await snap()).responses[0]);assert.equal((await snap()).step,0);await page.click('#retry-plan');await answer(bank[5]);assert.equal((await snap()).step,0);await page.click('#confirm-plan');assert.equal((await snap()).step,1);
  let cameraSamples=0,minWallClearance=Infinity;
  async function sweep(){const samples=await page.evaluate(()=>{const out=[];for(const radius of [4,27])for(const phi of [.2,.85,1.5]){let v=mtReview.view(),o=v.camera.map((x,i)=>x-v.look[i]),r=Math.hypot(...o);mtReview.orbit(0,phi-Math.acos(o[1]/r),radius/r);for(let angle=0;angle<24;angle++){v=mtReview.view();r=Math.hypot(...v.camera.map((x,i)=>x-v.look[i]));mtReview.orbit(Math.PI/12,0,radius/r);out.push(mtReview.view())}}return out});for(const v of samples){const margin=v.near*Math.sqrt(1+Math.tan(35*Math.PI/360)**2*(1+v.aspect**2));for(const b of v.walls){const d=Math.hypot(...v.camera.map((n,i)=>Math.max(b.min[i]-n,0,n-b.max[i])));assert.ok(d>margin,'Room/near-plane clipping');minWallClearance=Math.min(minWallClearance,d-margin)}cameraSamples++}await page.click('#home')}
  const projectShots=[];let originalCut;
  for(let i=1;i<plan.steps.length;i++){
    const st=plan.steps[i],c=bank.find(c=>c.id===st.exercise);assert.equal((await snap()).step,i);
    if(c?.targetLabel)assert.equal((await page.locator('#target').textContent()).trim(),c.targetLabel+' in');
    const before=(await snap()).parts.length;
    if(i===1){await page.uncheck('#reduced');await page.evaluate(()=>{mtReview.select(16);mtReview.cut();mtReview.cut()});assert.equal((await snap()).phase,'cutting');await page.waitForFunction(()=>mtReview.snapshot().phase==='approaching');assert.equal((await page.evaluate(()=>mtReview.view())).piece.length,2);await page.waitForFunction(()=>mtReview.snapshot().phase==='inspecting');await page.screenshot({path:path.join(evidence,'held-wrong-inspection.png')});await page.waitForTimeout(150);assert.equal((await snap()).phase,'inspecting');assert.equal((await snap()).attempts.length,1);originalCut=JSON.stringify((await snap()).attempts[0]);await page.evaluate(()=>mtReview.acknowledge());await page.waitForFunction(()=>mtReview.snapshot().phase==='selecting');assert.equal((await snap()).step,i);assert.equal((await snap()).parts.length,before)}
    await page.evaluate(n=>{mtReview.select(n);mtReview.cut()},st.length);
    const repair=c?.id==='MT-C03';if(c?.question)await answer(c,repair);if(i===1)await page.waitForFunction(()=>mtReview.snapshot().phase==='inspecting');
    assert.equal((await snap()).step,i,'No advance during held inspection');assert.equal((await snap()).parts.length,before);assert.equal((await snap()).phase,'inspecting');
    if(repair){const attempts=(await snap()).attempts.length,first=JSON.stringify((await snap()).responses.filter(r=>r.id===c.id)[0]);await page.evaluate(()=>mtReview.acknowledge());assert.equal((await snap()).step,i);assert.equal((await snap()).phase,'inspecting');await answer(c);assert.equal((await snap()).attempts.length,attempts,'Reasoning repair does not recut good wood');assert.equal(JSON.stringify((await snap()).responses.filter(r=>r.id===c.id)[0]),first);await page.click('#confirm-plan');assert.equal((await snap()).step,i)}
    // Leave and return to the same unacknowledged committed piece.
    if(i===7){await page.evaluate(()=>{mtReview.mode('learn');mtReview.chooseLesson(2);mtReview.mode('challenge')});assert.equal((await snap()).step,i);assert.equal((await snap()).phase,'inspecting')}
    await page.evaluate(()=>{mtReview.acknowledge();mtReview.acknowledge()});if(i===1){assert.equal((await snap()).step,i);await page.waitForFunction(()=>mtReview.snapshot().phase==='duplicating');assert.equal((await snap()).step,i);await page.waitForFunction(()=>mtReview.snapshot().phase==='assembling');assert.equal((await snap()).step,i);await page.waitForFunction(()=>mtReview.snapshot().step===2);await page.check('#reduced')}assert.equal((await snap()).step,i+1,'Advance automatically after placement');assert.equal((await snap()).parts.length,before+st.placements.length);
    const currentGeometry=await page.evaluate(()=>mtReview.geometry());for(const p of currentGeometry){assert.equal(p.meshLength,p.length/8);assert.deepEqual(p.scale,[1,1,1])}
    if(i===plan.steps.length-1||plan.steps[i+1].project!==st.project){await page.screenshot({path:path.join(evidence,st.project+'-complete.png')});projectShots.push(st.project);for(const viewport of [{width:1920,height:1080},{width:1366,height:768},{width:1024,height:768}]){await page.setViewportSize(viewport);await sweep()}await page.setViewportSize({width:1366,height:768})}
  }
  let s=await snap();assert.equal(JSON.stringify(s.responses[0]),originalChoice);assert.equal(JSON.stringify(s.attempts[0]),originalCut);assert.equal(s.parts.filter(p=>p.role==='frame').length,17);assert.equal((await status()).complete,true);assert.equal((await status()).correctCount,30);assert.deepEqual(projectShots,['chair','plane','house']);
  const count=s.parts.length,history=JSON.stringify(s.responses);await page.click('#previous-step');await page.click('#redo-step');assert.equal((await status()).complete,false);const st=plan.steps.at(-1),c=bank.find(c=>c.id===st.exercise);await page.evaluate(n=>{mtReview.select(n);mtReview.cut()},st.length-1);if(c?.question)await answer(c);await page.evaluate(()=>mtReview.acknowledge());assert.equal((await snap()).parts.length,count);assert.equal((await snap()).step,31);await page.evaluate(n=>{mtReview.select(n);mtReview.cut()},st.length);await page.evaluate(()=>mtReview.acknowledge());assert.equal((await snap()).parts.length,count,'Redo does not duplicate model pieces');assert.equal((await status()).complete,true);assert.equal(JSON.stringify((await snap()).responses.slice(0,JSON.parse(history).length)),history);
  await page.click('#checks');assert.equal(await page.locator('[data-check]').count(),0);assert.equal(await page.locator('[data-review]').count(),32);assert.equal(await page.locator('#completion-report').isEnabled(),true);await page.screenshot({path:path.join(evidence,'build-progress.png')});const downloaded=page.waitForEvent('download');await page.click('#completion-report');const download=await downloaded;assert.equal(download.suggestedFilename(),report.id+'_Challenge-Report.txt');const output=path.join(evidence,download.suggestedFilename());await download.saveAs(output);const text=fs.readFileSync(output,'utf8');for(const str of [report.id,report.sourceRevision,'Chair:','Plane:','House Exterior:','Original House Frame: 17/17','Teacher Review','Retry','Incorrect'])assert.ok(text.includes(str),str);for(const c of bank)assert.ok(text.includes(c.id));await page.click('#continue-build');
  await page.setViewportSize({width:1024,height:768});await page.screenshot({path:path.join(evidence,'house-laptop.png')});await page.click('#checks');await page.locator('[data-review="31"]').scrollIntoViewIfNeeded();assert.equal(await page.locator('[data-review="31"]').isVisible(),true);await page.click('#close-panel');
  const attempts=JSON.stringify((await snap()).attempts),responses=JSON.stringify((await snap()).responses);await page.evaluate(()=>mtReview.restart());assert.equal((await snap()).step,0);assert.equal((await snap()).parts.length,0);assert.equal((await status()).complete,false);assert.equal(JSON.stringify((await snap()).attempts),attempts);assert.equal(JSON.stringify((await snap()).responses),responses);await page.click('#plan-order');await page.click('#confirm-plan');await page.evaluate(()=>{mtReview.select(17);mtReview.cut()});assert.equal((await snap()).pending.assisted,true);assert.equal((await snap()).step,1);
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);const result={id:report.id,sourceRevision:report.sourceRevision,steps:32,exercises:30,projects:projectShots,parts:count,cameraSamples,minWallClearance,checks:['Full Saw and Camera Animation, Held Inspection and Placement Before Advance','1296 Camera Samples Across Three Projects and Three Viewports','Automatic Chair-Plane-House Sequence','No Required Exercise Picker','Held Unit-Order Confirmation','Wrong Cut Stays on Current Part','Good Wood Retained During Reasoning-Only Retry','No Premature Advance or Duplicate Award','Mode/Learn Visit Preserves Held Inspection','All Three Exact Models and Original 17 Frame Members','Completed-Step Review and Redo','Every Objective and Build Required for Report','Actual Offline Report Download','Restart Preserves Immutable History and Support','1024x768 and 1366x768'],errors,requests,syntheticStudentData:true};fs.writeFileSync(path.join(evidence,'sequential-verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await browser?.close();await new Promise(resolve=>server.close(resolve))}
})().catch(e=>{console.error(e);process.exitCode=1});
