import {createRecipes,recipePlan,catalogRevision} from './recipes.js';
import {createProgressStore,currentRun,startRun,completedRun} from './catalog-progress.js';
import {currentStep,finishStep,acknowledgeStep} from './construction.js';
import {newSession,fraction} from './model.js';
import {checks,provenance} from './content.js';
import {createMiniatures} from './miniatures.js';
import {retiredFitQuestions} from './support-history.js';

export function installCatalog(game){
  const {$,panel}=game,recipes=createRecipes(game.house,checks),escape=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  let storage;try{storage=localStorage}catch{storage={getItem(){throw Error('Unavailable')}}}
  const store=createProgressStore(storage,recipes),data=store.data,images=createMiniatures(game.THREE,recipes);
  const recipe=()=>recipes.find(r=>r.id===game.session.recipeId),plan=()=>recipePlan(recipe(),recipes),step=()=>currentStep(game.session,plan());
  const save=()=>{store.save();$('save-status').textContent=store.message};
  game.observeExposure(id=>{if(/^MT-C\d{2}$/.test(id)&&!data.supportExposed.includes(id)){data.supportExposed.push(id);save()}});
  const active=()=>Boolean(recipe()),done=(r,s)=>s&&completedRun(s,r),finished=r=>data.recipes[r.id].runs.filter(s=>done(r,s));
  function select(id,{replay=false}={}){const r=recipes.find(r=>r.id===id);if(!r)return false;game.settle();save();const s=startRun(data,r,{replay});$('panel').close();game.replaceChallenge(s,recipePlan(r,recipes));if(s.phase!=='inspecting')game.nextSelection();game.rebuildParts();save();return true;}
  function catalog(){game.settle();save();panel('<h2>Choose A Build</h2><p class="catalog-intro">Choose any model. Finish it to reveal its miniature. Return to continue or build it again.</p><div class="build-catalog">'+recipes.map(r=>{const s=currentRun(data,r.id),won=finished(r).length>0,continuing=s&&!done(r,s);return `<button class="build-tile" data-recipe="${r.id}" aria-label="${continuing?'Continue':won?'Replay':'Start'} ${r.title}">${won?`<img src="${images[r.id]}" alt="Completed ${r.title} Miniature">`:'<span class="mystery-model" aria-hidden="true">?</span>'}<strong>${r.title}</strong><small>${r.partCount} Pieces · ${r.steps.length} Measurements</small><span class="tile-action">${continuing?`Continue ${s.step}/${r.steps.length}`:won?'Build Again':'Start Building'}${won?' · ✓':''}</span></button>`}).join('')+'</div><p class="catalog-storage">'+escape(store.message)+'</p><div class="catalog-actions"><button id="catalog-records">Export Progress</button><button id="question-bank">Supporting Questions</button></div>');
    document.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>select(b.dataset.recipe));$('catalog-records').onclick=exportProgress;$('question-bank').onclick=questionBank;
  }
  function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function exportProgress(){save();download((game.manifest?.id??'Measure-Twice')+'_Catalog-Progress.json',JSON.stringify({schemaVersion:1,build:game.manifest,contentRevision:provenance.revision,catalogRevision,exportedAt:new Date().toISOString(),progress:data,limits:'Build completion records exact cuts and automatic placement. It does not mean all 30 supporting questions were answered or independently explained.'},null,2),'application/json');}
  function reportText(){const lines=['Measure Twice Build Report','',`Build: ${game.manifest?.id??'Unbuilt'}`,`Built At UTC: ${game.manifest?.builtAt??'Unknown'}`,`Source Revision: ${game.manifest?.sourceRevision??'Unknown'}`,`Catalog Revision: ${catalogRevision}`,`Exported At UTC: ${new Date().toISOString()}`,'','This report records chosen builds and replays. The 30 supporting questions are separate reference material, not a completion gate or an automatic score. Automatic assembly does not establish independent reasoning or physical fabrication mastery.',''];for(const r of recipes){lines.push(`${r.title}: ${finished(r).length} Completed Runs; ${r.partCount} Parts Per Complete Model`);for(const s of data.recipes[r.id].runs){lines.push(`Run ${s.runNumber}: ${done(r,s)?'Complete':'Partial'}; ${s.builtSteps.length}/${r.steps.length} Measurements Placed; ${s.parts.length}/${r.partCount} Parts`);for(const a of s.attempts)lines.push(`${a.context} | Actual ${fraction(a.actual)} in | Target ${fraction(a.target)} in | ${a.correct?'Correct':'Incorrect'} | ${a.assisted?'Assisted / Previously Exposed':'No Recorded Assistance'} | ${a.retry?'Retry':'Original'} | ${a.recordedAt}`);}}lines.push('',`Supporting Questions Viewed: ${data.supportViewed.join(', ')||'None'}`,`Related Learn / Reference Support Exposed: ${data.supportExposed.join(', ')||'None'}`);return lines.join('\n');}
  function report(){download((game.manifest?.id??'Measure-Twice')+'_Build-Report.txt',reportText(),'text/plain;charset=utf-8');}
  function progress(){const r=recipe(),s=game.session;if(!r)return catalog();panel(`<h2>${r.title} Progress</h2><p>Run ${s.runNumber}: ${s.builtSteps.length} of ${r.steps.length} measurements placed, ${s.parts.length} of ${r.partCount} pieces.</p><ol>`+r.steps.map((st,i)=>`<li>${escape(st.title)} · ${fraction(st.length)} in · ${st.placements.length} ${st.placements.length===1?'Piece':'Pieces'} · ${s.builtSteps.includes(st.id)?'Placed':i===s.step?'Current':'Coming Later'}</li>`).join('')+'</ol><button id="return-build">Return To Build</button><button id="choose-build">Choose A Build</button><button id="build-report">Download Build Report</button><button id="catalog-records">Export Progress</button><button id="question-bank">Supporting Questions</button>');$('return-build').onclick=()=>$('panel').close();$('choose-build').onclick=catalog;$('build-report').onclick=report;$('catalog-records').onclick=exportProgress;$('question-bank').onclick=questionBank;}
  function questionBank(){panel('<h2>Supporting Questions</h2><p>The original 30 questions remain available here. Their answers are support; viewing them is recorded separately. Five fit questions retired in the earlier teacher review are labeled as historical references. Archived wording is preserved below; this bank does not collect or save written answers. Completing a model does not claim that you answered this bank.</p><div class="support-bank">'+checks.map(c=>`<details data-support="${c.id}"><summary>${c.id} · ${escape(c.title)}${retiredFitQuestions.includes(c.id)?' (Historical Fit Reference)':''}</summary><p>${escape(c.prompt)}</p>${c.question?`<p>${escape(c.question)}</p>`:''}<p>${escape(c.feedback)}</p><small>DM 1.3 ${escape(c.goals.join(', '))} · ${escape(c.pages)}</small></details>`).join('')+'</div><button id="choose-build">Back To Builds</button>');$('choose-build').onclick=catalog;document.querySelectorAll('[data-support]').forEach(el=>el.ontoggle=()=>{if(el.open){const id=el.dataset.support;if(!data.supportViewed.includes(id))data.supportViewed.push(id);game.expose(id);save();}});}
  const chooseButton=document.createElement('button');chooseButton.id='choose-builds';chooseButton.textContent='Choose A Build';$('challenge-controls').prepend(chooseButton);chooseButton.onclick=catalog;
  const saveStatus=document.createElement('span');saveStatus.id='save-status';saveStatus.className='save-status';$('challenge-controls').append(saveStatus);
  game.routeChallenge({
    target:()=>step()?.length??null,context:()=>step()?.id??'catalog',copyCount:()=>step()?.placements.length??1,
    isComplete:s=>!active()||s.step>=recipe().steps.length,
    selecting:s=>{s.activity='catalog';s.subdivision=step()?.scale??16;},
    beforeCut:s=>{if(!active()||!step()||s.phase!=='selecting')return false;const q=step().supportingQuestion;if(s.runNumber>1||q&&(data.supportViewed.includes(q)||data.supportExposed.includes(q)))s.hint=true;return true;},
    acknowledge:s=>acknowledgeStep(s,plan(),[]),kept:s=>{finishStep(s,plan());if(s.step===recipe().steps.length)s.completedAt=new Date().toISOString();},
    inspected:save,updatedInput:save,
    restart:()=>{if(recipe())select(recipe().id,{replay:true});else catalog();return false;},
    modeEntered:catalog,
    update:s=>{
      const r=recipe(),st=step(),complete=r&&done(r,s);$('guidance').hidden=true;$('readout').hidden=false;$('dock').hidden=false;$('previous-step').hidden=true;$('plan-order').hidden=true;$('hint').hidden=!r;
      $('kicker').textContent=r?`${r.title} · Run ${s.runNumber}`:'Your Build Collection';$('order-title').textContent=st?.title??(r?r.title+' Complete':'Choose A Build');$('order-note').textContent=st?`Cut ${fraction(st.length)} inches. ${st.placements.length===1?'Keep this one piece.':`Keep one original and make ${st.placements.length-1} equal ${st.placements.length===2?'copy':'copies'} for this part.`}`:r?'Your miniature is ready in the collection. Choose another build or replay this one.':'House, plane, chair, or tree: choose where to begin.';
      $('target').hidden=!st;$('cut-label').hidden=!st;$('progress').textContent=r?`${s.parts.length} of ${r.partCount} Pieces`:'Four Builds To Choose From';$('evidence').textContent=r?`${s.builtSteps.length} of ${r.steps.length} Measurements Placed`:'Your Progress Saves In This Browser';$('checks').textContent='Build Progress';$('checks').onclick=progress;$('hint').onclick=()=>{s.hint=true;game.expose(st?.id);panel('<h2>A Measuring Hint</h2><p>Begin at zero. Count the visible intervals for the requested length. The number of copies includes the retained original.</p>');save()};
      $('complete').hidden=true;if(complete)$('phase').textContent=r.title+' Complete';$('object-cue').textContent='Drag the workshop to inspect your model. Drag the blue cutting pointer to set a measurement.';
      $('cut').disabled=!st||s.phase!=='selecting'||s.selected===0;$('save-status').textContent=store.message;save();
    }
  });
  game.catalogPractice=()=>{const st=step(),c=checks.find(c=>c.id===st?.supportingQuestion);game.showCurriculum(c??{objective:'Read a fractional-inch length from visible graduations, cut it, and compare the actual and requested spans. The Tree is an original practice model.',goals:['G10','G11','G13'],pages:'Activity 1.3, measurement reference'})};
  window.mtReview.catalog=()=>structuredClone(data);window.mtReview.recipes=()=>structuredClone(recipes);window.mtReview.selectRecipe=select;window.mtReview.openCatalog=catalog;window.mtReview.openQuestionBank=questionBank;window.mtReview.reportText=reportText;window.mtReview.challengeStatus=()=>({active:recipe()?.id??null,complete:recipe()?done(recipe(),game.session):false,completedRecipes:recipes.filter(r=>finished(r).length).map(r=>r.id)});window.mtReview.plan=plan;
  const saved=data.activeRecipeId&&currentRun(data,data.activeRecipeId);game.replaceChallenge(saved||{...newSession('challenge'),activity:'catalog',phase:'complete'},recipePlan(saved?recipes.find(r=>r.id===saved.recipeId):null,recipes));if(!saved||saved.phase!=='inspecting')game.nextSelection();game.rebuildParts();catalog();
}
