// Original teaching summaries from the approved MeasureTwice content record.
export const provenance={revision:'2026-09-30',audit:'1713a3bd537035f2ce09dfc7fe05ce6bf6b70cc3',source:'https://github.com/AbbyUsesAIThatCodes/DesignAndModeling26-27/blob/1713a3bd537035f2ce09dfc7fe05ce6bf6b70cc3/units/01-introduction-to-design/1.3-measuring-matters/teacher-guides/measuring-matters-curricular-goals.pdf',review:'Teacher Review Build; Selected Primary Pages Verified September 30, 2026'};
export const lessons=[
  {id:'MT-L01',title:'Start At Zero',goals:['G07','G10','G16'],pages:'A p. 5, p. 11, pp. 37–38, p. 66',objective:'Find the starting graduation and count equal intervals, with a value and unit.',text:'Start at the zero mark. The edge of the ruler may stick out past it. Count the intervals after zero. A measurement needs a number and a unit; here the unit is the inch.',guided:6,practice:10,scale:8,demo:[0,2,4,6],demoText:'Watch three eighth-inch spaces grow from the zero graduation to 3/8 in.',prompt:'Mark 3/8 inch.',practicePrompt:'Try 5/8 inch without a solved readout.',feedback:'Three eighth-inch spaces take you from zero to 3/8 inch. Check the starting graduation, not the ruler edge.',check:'MT-C01',question:'Which starting mark should you use?',options:['The Zero Graduation','The Physical Ruler Edge'],answer:'The Zero Graduation'},
  {id:'MT-L02',title:'Meet The Fractions',goals:['G10','G11'],pages:'A step 3, pp. 11–25',objective:'Interpret equal subdivisions through sixteenths.',text:'One inch can be divided into equal parts. More parts mean smaller intervals. The one-inch whole stays the same length.',guided:10,practice:7,scale:8,demo:[8,8,8,8],demoScales:[2,4,8,16],demoText:'The one-inch whole stays fixed while halves become quarters, eighths, and sixteenths.',prompt:'Mark 5/8 inch.',practicePrompt:'Try 7/16 inch.',feedback:'Count how many equal intervals make one inch, then count the intervals from zero.',check:'MT-C02'},
  {id:'MT-L03',title:'Same Length, Different Names',goals:['G12'],pages:'A pp. 15, 17–21, 23, 25',objective:'Recognize equivalent fractions at the same ruler position.',text:'Changing a fraction’s name does not always change its length. Three quarters and six eighths cover the same part of one inch.',guided:12,practice:4,scale:8,demo:[8,8,8,8],demoScales:[2,4,8,16],demoText:'One fixed endpoint: 1/2 = 2/4 = 4/8 = 8/16 inch.',prompt:'Mark 3/4 inch. Then compare it with 6/8 inch.',practicePrompt:'Predict whether 2/8 inch and 1/4 inch coincide.',feedback:'Equal spans end at the same ruler position: 3/4 = 6/8 and 1/4 = 2/8.',check:'MT-C03',question:'Would 3/4 inch and 6/8 inch land together?',options:['Yes, the Same Endpoint','No, Different Endpoints'],answer:'Yes, the Same Endpoint'},
  {id:'MT-L04',title:'Whole Inches And A Little More',goals:['G13'],pages:'A step 6, p. 39',objective:'Combine whole inches with a fractional remainder.',text:'Read the whole inches first. Then add the fraction beyond that whole-inch mark. Do not drop the whole inch at the beginning.',guided:19,practice:26,scale:16,demo:[16,32,36],demoText:'Two whole inches, then one quarter more: 2 1/4 in. Compare that with only 1/4 in.',prompt:'Mark 1 3/16 inches.',practicePrompt:'Try 1 5/8 inches.',feedback:'One whole inch plus three sixteenths is 1 3/16 in. A 3/16-in piece is one whole inch too short.',check:'MT-C04'},
  {id:'MT-L05',title:'Will It Fit?',goals:['G08','G07','G11'],pages:'A pp. 5, 42, 47, 66; fractional reading pp. 11–25',objective:'Explain how an inaccurate measurement changes fit.',text:'A part can look nearly right and still leave a gap. Compare its measured length with the length needed. A 1 1/8-in piece cannot fill a 1 1/4-in opening.',guided:20,practice:20,scale:16,demo:[18],demoCut:18,demoText:'Worked example: cut 1 1/8 in for a 1 1/4-in opening, then inspect the missing 1/8 in.',prompt:'Mark the needed 1 1/4 inches.',practicePrompt:'A 1 3/8-in piece is too long. Predict the corrected 1 1/4-in cut.',feedback:'Too little length leaves a gap. Extra length extends beyond the opening. The difference here is 1/8 in.',check:'MT-C05',question:'Why does the 1 1/8-in piece leave a gap?',options:['It Is Shorter Than the Opening','Its Color Is Different'],answer:'It Is Shorter Than the Opening'}
];
export const checks=[
  {id:'MT-C01',title:'Find the Starting Graduation',lesson:0,target:6,scale:8,goals:['G10','G11','G16'],prompt:'Mark 3/8 inch. Select where your measurement begins.',question:'Where does the measurement begin?',options:['The Zero Graduation','The Physical Ruler Edge'],answer:'The Zero Graduation',feedback:'Begin at the zero graduation. Three eighth-inch spaces give 3/8 in. The physical edge may extend before zero.',kind:'cut'},
  {id:'MT-C02',title:'Read Sixteenths',lesson:1,target:7,scale:16,goals:['G11'],prompt:'Cut a piece 7/16 inch long.',feedback:'Seven equal sixteenth-inch intervals from zero give 7/16 in.',kind:'cut'},
  {id:'MT-C03',title:'Compare Equivalent Names',lesson:2,target:12,targetLabel:'6/8',scale:8,goals:['G12'],prompt:'Mark 6/8 inch. Would a 3/4-inch piece have the same length? Explain.',question:'Would they have the same length?',options:['Yes, the Same Endpoint','No, Different Endpoints'],answer:'Yes, the Same Endpoint',explanation:true,feedback:'Yes. Six eighths and three quarters span the same length and end at the same position. Your written reasoning is saved for teacher review.',kind:'cut'},
  {id:'MT-C04',title:'Keep the Whole Inch',lesson:3,target:19,scale:16,goals:['G13'],prompt:'Cut an upright 1 3/16 inches long.',feedback:'Keep the whole inch, then count three sixteenths. A 3/16-in response is one inch too short.',kind:'cut'},
  {id:'MT-C05',title:'Predict the Fit',lesson:4,target:null,scale:16,goals:['G08','G07','G11'],prompt:'This opening needs 1 1/4 inches. Your piece measures 1 1/8 inches. Will it fit correctly? Why?',question:'Predict the fit before seeing the diagnosis.',options:['Too Short','Too Long','The Right Length'],answer:'Too Short',explanation:true,feedback:'It is 1/8 in too short and leaves a gap because its length is less than the opening. Your written explanation is for teacher review; viewing this feedback is not an independent response.',kind:'concept'},
  {id:'MT-C06',title:'Name the Missing Information',lesson:0,target:null,scale:16,goals:['G07'],prompt:'The order says “length: 2.” What information is missing?',question:'Choose the missing information.',options:['The Unit','The Wood Color','The Saw Speed'],answer:'The Unit',feedback:'The unit is missing. Two inches and two centimeters are different lengths. Normal orders need both a value and a unit.',kind:'concept'}
];
