// Original teaching summaries from the approved MeasureTwice content record.
export const provenance={revision:'2026-09-30-bank-30-v1',audit:'1713a3bd537035f2ce09dfc7fe05ce6bf6b70cc3',source:'https://github.com/AbbyUsesAIThatCodes/DesignAndModeling26-27/blob/1713a3bd537035f2ce09dfc7fe05ce6bf6b70cc3/units/01-introduction-to-design/1.3-measuring-matters/teacher-guides/measuring-matters-curricular-goals.pdf',review:'Teacher Review Build; Selected Primary Pages Verified September 30, 2026'};
export const lessons=[
  {id:'MT-L01',title:'Start at Zero',goals:['G07','G10','G16'],pages:'A p. 5, p. 11, pp. 37–38, p. 66',objective:'Find the starting graduation and count equal spaces, with a value and unit.',text:'Start at the zero mark. The edge of the ruler may stick out past it. Count the spaces after zero. A measurement needs a number and a unit; here the unit is the inch.',guided:6,practice:10,scale:8,demo:[0,2,4,6],demoText:'Watch three eighth-inch spaces grow from the zero graduation to 3/8 in.',prompt:'Mark 3/8 inch.',practicePrompt:'Try 5/8 inch without a solved readout.',feedback:'Three eighth-inch spaces take you from zero to 3/8 inch. Check the starting graduation, not the ruler edge.',check:'MT-C01',question:'Which starting mark should you use?',options:['The Zero Graduation','The Physical Ruler Edge'],answer:'The Zero Graduation'},
  {id:'MT-L02',title:'Meet the Fractions',goals:['G10','G11'],pages:'A step 3, pp. 11–25',objective:'Interpret equal subdivisions through sixteenths.',text:'One inch can be divided into equal parts. More parts mean smaller spaces. The one-inch whole stays the same length.',guided:10,practice:7,scale:8,demo:[8,8,8,8],demoScales:[2,4,8,16],demoText:'The one-inch whole stays fixed while halves become quarters, eighths, and sixteenths.',prompt:'Mark 5/8 inch.',practicePrompt:'Try 7/16 inch.',feedback:'Count how many equal spaces make one inch, then count the spaces from zero.',check:'MT-C02'},
  {id:'MT-L03',title:'Same Length, Different Names',goals:['G12'],pages:'A pp. 15, 17–21, 23, 25',objective:'Recognize equivalent fractions at the same ruler position.',text:'Changing a fraction’s name does not always change its length. Three quarters and six eighths cover the same part of one inch.',guided:12,practice:4,scale:8,demo:[8,8,8,8],demoScales:[2,4,8,16],demoText:'One fixed endpoint: 1/2 = 2/4 = 4/8 = 8/16 inch.',prompt:'Mark 3/4 inch. Then compare it with 6/8 inch.',practicePrompt:'Predict whether 2/8 inch and 1/4 inch coincide.',feedback:'Equal spans end at the same ruler position: 3/4 = 6/8 and 1/4 = 2/8.',check:'MT-C03',question:'Would 3/4 inch and 6/8 inch land together?',options:['Yes, the Same Endpoint','No, Different Endpoints'],answer:'Yes, the Same Endpoint'},
  {id:'MT-L04',title:'Whole Inches and a Little More',goals:['G13'],pages:'A step 6, p. 39',objective:'Combine whole inches with a fractional remainder.',text:'Read the whole inches first. Then add the fraction beyond that whole-inch mark. Do not drop the whole inch at the beginning. For equal-part planning, count the retained original as one part; add only the remaining copies. Copies keep the same measured length.',guided:19,practice:26,scale:16,demo:[16,32,36],demoText:'Two whole inches, then one quarter more: 2 1/4 in. Compare that with only 1/4 in.',prompt:'Mark 1 3/16 inches.',practicePrompt:'Try 1 5/8 inches.',feedback:'One whole inch plus three sixteenths is 1 3/16 in. A 3/16-in piece is one whole inch too short.',check:'MT-C04'},
  {id:'MT-L05',title:'Will It Fit?',goals:['G08','G07','G11'],pages:'A pp. 5, 42, 47, 66; fractional reading pp. 11–25',objective:'Explain how an inaccurate measurement changes fit.',text:'A part can look nearly right and still leave a gap. Compare its measured length with the length needed. A 1 1/8-in piece cannot fill a 1 1/4-in opening.',guided:20,practice:20,scale:16,demo:[18],demoCut:18,demoText:'Worked example: cut 1 1/8 in for a 1 1/4-in opening, then inspect the missing 1/8 in.',prompt:'Mark the needed 1 1/4 inches.',practicePrompt:'A 1 3/8-in piece is too long. Predict the corrected 1 1/4-in cut.',feedback:'Too little length leaves a gap. Extra length extends beyond the opening. The difference here is 1/8 in.',check:'MT-C05',question:'Why does the 1 1/8-in piece leave a gap?',options:['It Is Shorter Than the Opening','Its Color Is Different'],answer:'It Is Shorter Than the Opening'}
];
export const checks=[
  {id:'MT-C01',title:'Find the Starting Graduation',lesson:0,target:6,scale:8,goals:['G10','G11','G16'],prompt:'Mark 3/8 inch. Select where your measurement begins.',question:'Where does the measurement begin?',options:['The Zero Graduation','The Physical Ruler Edge'],answer:'The Zero Graduation',feedback:'Begin at the zero graduation. Three eighth-inch spaces give 3/8 in. The physical edge may extend before zero.',kind:'cut'},
  {id:'MT-C02',title:'Read Sixteenths',lesson:1,target:7,scale:16,goals:['G11'],prompt:'Cut a piece 7/16 inch long.',feedback:'Seven equal sixteenth-inch spaces from zero give 7/16 in.',kind:'cut'},
  {id:'MT-C03',title:'Compare Equivalent Names',lesson:2,target:12,targetLabel:'6/8',scale:8,goals:['G12'],prompt:'Mark 6/8 inch. Would a 3/4-inch piece have the same length? Explain.',question:'Would they have the same length?',options:['Yes, the Same Endpoint','No, Different Endpoints'],answer:'Yes, the Same Endpoint',explanation:true,feedback:'Yes. Six eighths and three quarters span the same length and end at the same position. Your written reasoning is saved for teacher review.',kind:'cut'},
  {id:'MT-C04',title:'Keep the Whole Inch',lesson:3,target:19,scale:16,goals:['G13'],prompt:'Cut an upright 1 3/16 inches long.',feedback:'Keep the whole inch, then count three sixteenths. A 3/16-in response is one inch too short.',kind:'cut'},
  {id:'MT-C05',title:'Predict the Fit',lesson:4,target:null,scale:16,goals:['G08','G07','G11'],prompt:'This opening needs 1 1/4 inches. Your piece measures 1 1/8 inches. Will it fit correctly? Why?',question:'Predict the fit before seeing the diagnosis.',options:['Too Short','Too Long','The Right Length'],answer:'Too Short',explanation:true,feedback:'It is 1/8 in too short and leaves a gap because its length is less than the opening. Your written explanation is for teacher review; viewing this feedback is not an independent response.',comparison:{actual:18,needed:20},kind:'concept'},
  {id:'MT-C06',title:'Name the Missing Information',lesson:0,target:null,scale:16,goals:['G07'],prompt:'The order says “length: 2.” What information is missing?',question:'Choose the missing information.',options:['The Unit','The Wood Color','The Saw Speed'],answer:'The Unit',feedback:'The unit is missing. Two inches and two centimeters are different lengths. Normal orders need both a value and a unit.',kind:'concept'}
,
  {"id": "MT-C07", "title": "Fraction Cut 1", "lesson": 1, "target": 8, "scale": 2, "goals": ["G10", "G11"], "prompt": "Cut a 1/2-inch spacer. Read the printed marks from zero.", "feedback": "The spacer needs 1/2 in. Compare your actual endpoint with that requested length.", "kind": "cut"},
  {"id": "MT-C08", "title": "Fraction Cut 2", "lesson": 1, "target": 4, "scale": 4, "goals": ["G10", "G11"], "prompt": "Cut a 1/4-inch spacer. Read the printed marks from zero.", "feedback": "The spacer needs 1/4 in. Compare your actual endpoint with that requested length.", "kind": "cut"},
  {"id": "MT-C09", "title": "Fraction Cut 3", "lesson": 1, "target": 14, "scale": 8, "goals": ["G10", "G11"], "prompt": "Cut a 7/8-inch spacer. Read the printed marks from zero.", "feedback": "The spacer needs 7/8 in. Compare your actual endpoint with that requested length.", "kind": "cut"},
  {"id": "MT-C10", "title": "Fraction Cut 4", "lesson": 1, "target": 1, "scale": 16, "goals": ["G10", "G11"], "prompt": "Cut a 1/16-inch spacer. Read the printed marks from zero.", "feedback": "The spacer needs 1/16 in. Compare your actual endpoint with that requested length.", "kind": "cut"},
  {"id": "MT-C11", "title": "Fraction Cut 5", "lesson": 1, "target": 11, "scale": 16, "goals": ["G10", "G11"], "prompt": "Cut an 11/16-inch spacer. Read the printed marks from zero.", "feedback": "The spacer needs 11/16 in. Compare your actual endpoint with that requested length.", "kind": "cut"},
  {"id": "MT-C12", "title": "Fraction Cut 6", "lesson": 1, "target": 15, "scale": 16, "goals": ["G10", "G11"], "prompt": "Cut a 15/16-inch spacer. Read the printed marks from zero.", "feedback": "The spacer needs 15/16 in. Compare your actual endpoint with that requested length.", "kind": "cut"},
  {"id": "MT-C13", "title": "Longer Cut 1", "lesson": 3, "target": 17, "scale": 16, "goals": ["G11", "G13"], "prompt": "Cut a rail 1 1/16 inches long. Keep every whole inch.", "feedback": "The rail needs 1 1/16 in. Whole inches and the remaining fraction belong to one length.", "kind": "cut"},
  {"id": "MT-C14", "title": "Longer Cut 2", "lesson": 3, "target": 30, "scale": 16, "goals": ["G11", "G13"], "prompt": "Cut a rail 1 7/8 inches long. Keep every whole inch.", "feedback": "The rail needs 1 7/8 in. Whole inches and the remaining fraction belong to one length.", "kind": "cut"},
  {"id": "MT-C15", "title": "Longer Cut 3", "lesson": 3, "target": 35, "scale": 16, "goals": ["G11", "G13"], "prompt": "Cut a rail 2 3/16 inches long. Keep every whole inch.", "feedback": "The rail needs 2 3/16 in. Whole inches and the remaining fraction belong to one length.", "kind": "cut"},
  {"id": "MT-C16", "title": "Longer Cut 4", "lesson": 3, "target": 40, "scale": 16, "goals": ["G11", "G13"], "prompt": "Cut a rail 2 1/2 inches long. Keep every whole inch.", "feedback": "The rail needs 2 1/2 in. Whole inches and the remaining fraction belong to one length.", "kind": "cut"},
  {"id": "MT-C17", "title": "Longer Cut 5", "lesson": 3, "target": 47, "scale": 16, "goals": ["G11", "G13"], "prompt": "Cut a rail 2 15/16 inches long. Keep every whole inch.", "feedback": "The rail needs 2 15/16 in. Whole inches and the remaining fraction belong to one length.", "kind": "cut"},
  {"id": "MT-C18", "title": "Longer Cut 6", "lesson": 3, "target": 48, "scale": 16, "goals": ["G11", "G13"], "prompt": "Cut a rail 3 inches long. Keep every whole inch.", "feedback": "The rail needs 3 in. Whole inches and the remaining fraction belong to one length.", "kind": "cut"},
  {"id": "MT-C19", "title": "Equivalent Cut 1", "lesson": 2, "target": 8, "scale": 16, "goals": ["G11", "G12"], "prompt": "Mark 2/4 inch. Compare that length with 1/2 inch, then cut your prediction.", "feedback": "2/4 inch and 1/2 inch end together. Compare the measured spans; the inch stays the same.", "kind": "cut", "targetLabel": "2/4", "question": "Do 2/4 inch and 1/2 inch have the same length?", "options": ["Yes, the Same Endpoint", "No, Different Endpoints"], "answer": "Yes, the Same Endpoint", "explanation": true},
  {"id": "MT-C20", "title": "Equivalent Cut 2", "lesson": 2, "target": 6, "scale": 16, "goals": ["G11", "G12"], "prompt": "Mark 6/16 inch. Compare that length with 3/4 inch, then cut your prediction.", "feedback": "6/16 inch and 3/4 inch end at different positions. Compare the measured spans; the inch stays the same.", "kind": "cut", "targetLabel": "6/16", "question": "Do 6/16 inch and 3/4 inch have the same length?", "options": ["Yes, the Same Endpoint", "No, Different Endpoints"], "answer": "No, Different Endpoints", "explanation": true},
  {"id": "MT-C21", "title": "Equivalent Cut 3", "lesson": 2, "target": 20, "scale": 16, "goals": ["G11", "G12"], "prompt": "Mark 10/8 inch. Compare that length with 1 1/4 inch, then cut your prediction.", "feedback": "10/8 inch and 1 1/4 inch end together. Compare the measured spans; the inch stays the same.", "kind": "cut", "targetLabel": "10/8", "question": "Do 10/8 inch and 1 1/4 inch have the same length?", "options": ["Yes, the Same Endpoint", "No, Different Endpoints"], "answer": "Yes, the Same Endpoint", "explanation": true},
  {"id": "MT-C22", "title": "Equivalent Cut 4", "lesson": 2, "target": 28, "scale": 16, "goals": ["G11", "G12"], "prompt": "Mark 14/8 inch. Compare that length with 1 1/2 inch, then cut your prediction.", "feedback": "14/8 inch and 1 1/2 inch end at different positions. Compare the measured spans; the inch stays the same.", "kind": "cut", "targetLabel": "14/8", "question": "Do 14/8 inch and 1 1/2 inch have the same length?", "options": ["Yes, the Same Endpoint", "No, Different Endpoints"], "answer": "No, Different Endpoints", "explanation": true},
  {"id": "MT-C23", "title": "Fit and Cut 1", "lesson": 4, "target": 11, "scale": 16, "goals": ["G08", "G07", "G11"], "prompt": "An opening needs 11/16 inches. The sample is 9/16 inches. Predict its fit, then cut a new piece to the needed length.", "feedback": "The sample is too short. The new piece needs 11/16 in. Compare the aligned ends after commitment.", "kind": "cut", "question": "How does the sample fit the opening?", "options": ["Too Short", "Too Long", "The Right Length"], "answer": "Too Short", "explanation": true, "comparison": {"actual": 9, "needed": 11}},
  {"id": "MT-C24", "title": "Fit and Cut 2", "lesson": 4, "target": 25, "scale": 16, "goals": ["G08", "G07", "G11"], "prompt": "An opening needs 1 9/16 inches. The sample is 1 11/16 inches. Predict its fit, then cut a new piece to the needed length.", "feedback": "The sample is too long. The new piece needs 1 9/16 in. Compare the aligned ends after commitment.", "kind": "cut", "question": "How does the sample fit the opening?", "options": ["Too Short", "Too Long", "The Right Length"], "answer": "Too Long", "explanation": true, "comparison": {"actual": 27, "needed": 25}},
  {"id": "MT-C25", "title": "Fit and Cut 3", "lesson": 4, "target": 36, "scale": 16, "goals": ["G08", "G07", "G11"], "prompt": "An opening needs 2 1/4 inches. The sample is 2 1/4 inches. Predict its fit, then cut a new piece to the needed length.", "feedback": "The sample is the right length. The new piece needs 2 1/4 in. Compare the aligned ends after commitment.", "kind": "cut", "question": "How does the sample fit the opening?", "options": ["Too Short", "Too Long", "The Right Length"], "answer": "The Right Length", "explanation": true, "comparison": {"actual": 36, "needed": 36}},
  {"id": "MT-C26", "title": "Fit and Cut 4", "lesson": 4, "target": 48, "scale": 16, "goals": ["G08", "G07", "G11"], "prompt": "An opening needs 3 inches. The sample is 2 7/8 inches. Predict its fit, then cut a new piece to the needed length.", "feedback": "The sample is too short. The new piece needs 3 in. Compare the aligned ends after commitment.", "kind": "cut", "question": "How does the sample fit the opening?", "options": ["Too Short", "Too Long", "The Right Length"], "answer": "Too Short", "explanation": true, "comparison": {"actual": 46, "needed": 48}},
  {"id": "MT-C27", "title": "Origin and Cut 1", "lesson": 0, "target": 3, "scale": 16, "goals": ["G10", "G11", "G16"], "prompt": "Choose the correct starting reference and cut 3/16 inch.", "feedback": "The zero graduation is the origin. Measure 3/16 inch from it; the physical edge may extend past zero.", "kind": "cut", "question": "Which starting reference measures this length?", "options": ["The Zero Graduation", "The Physical Ruler Edge"], "answer": "The Zero Graduation"},
  {"id": "MT-C28", "title": "Origin and Cut 2", "lesson": 0, "target": 37, "scale": 16, "goals": ["G10", "G11", "G16"], "prompt": "Choose the correct starting reference and cut 2 5/16 inch.", "feedback": "The zero graduation is the origin. Measure 2 5/16 inch from it; the physical edge may extend past zero.", "kind": "cut", "question": "Which starting reference measures this length?", "options": ["The Zero Graduation", "The Physical Ruler Edge"], "answer": "The Zero Graduation"},
  {"id": "MT-C29", "title": "Equal Parts 1", "lesson": 3, "target": 22, "scale": 16, "goals": ["G11", "G13"], "prompt": "Make 3 equal 1 3/8-inch pieces. One successful cut is kept as the original. Predict how many additional copies are needed, then cut.", "feedback": "Keep the original and add 2 copies for 3 equal parts. Each part remains 1 3/8 in; none is stretched.", "kind": "cut", "question": "How many additional copies, after retaining the original?", "options": ["3", "2", "4"], "answer": "2", "copies": 3, "extension": "Equal-copy planning is a local construction extension; the measured cut practices G11/G13."},
  {"id": "MT-C30", "title": "Equal Parts 2", "lesson": 3, "target": 34, "scale": 16, "goals": ["G11", "G13"], "prompt": "Make 5 equal 2 1/8-inch pieces. One successful cut is kept as the original. Predict how many additional copies are needed, then cut.", "feedback": "Keep the original and add 4 copies for 5 equal parts. Each part remains 2 1/8 in; none is stretched.", "kind": "cut", "question": "How many additional copies, after retaining the original?", "options": ["5", "4", "6"], "answer": "4", "copies": 5, "extension": "Equal-copy planning is a local construction extension; the measured cut practices G11/G13."}
];

// Student-facing prompts and arithmetic targets are separate, including unreduced fractions.
for(const c of checks){c.pages=lessons[c.lesson].pages;c.mapping=c.extension?"Source-Backed Measurement; Local Copy-Planning Extension":"Source-Backed Digital Practice";}
