import {lessons,checks,provenance} from './content.js';
import {submitResponse,hasExposure,beginRetry,responseRound} from './model.js';
import {exerciseStatus,challengeStatus,teacherReport} from './assessment.js';
export function installLearning(game){
  const {$,panel}=game;let demoToken=0,activeDemo=null;
  const lesson=()=>lessons[game.session.lesson],check=()=>checks[game.session.check];
  const escape=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  const vocab=(word,definition,nested='')=>`<details class="vocab"><summary>${word}</summary><div>${definition}${nested}<p><a href="docs/curriculum-content.md" target="_blank" rel="noreferrer">Open the Reference</a></p></div></details>`;
  function exposeLesson(i){game.expose(lessons[i].id);for(const c of checks.filter(c=>c.lesson===i))game.expose(c.id)}
  function curriculum(entry){for(const c of checks.filter(c=>c.lesson===0||c.lesson===2))game.expose(c.id);panel(`<h2>${entry?'What This Practices':'Curriculum'}</h2><p>${entry?entry.objective||entry.prompt:'Read fractional inches, preserve the whole-inch part, compare equivalent names, and explain how a measured part fits.'}</p><p>${entry?'DM 1.3 '+entry.goals.join(', '):'DM 1.3 G07, G08, G10–G13 and G16'} · ${entry?.pages||lessons[entry?.lesson||0]?.pages}.</p><p>Choose bold vocabulary to keep its explanation open while exploring nested terms.</p>${vocab('Graduation','A marked position on a ruler. Zero is a starting graduation; the physical edge can extend beyond it.',vocab('Interval','The space between two neighboring graduations. Equal intervals represent equal lengths.'))}${vocab('Equivalent Fractions','Different fraction names for the same portion of one whole.',vocab('Unit','The agreed size being counted. Our unit is the inch.'))}<p>Cut commitments and separate explanations are evidence. Fixed zero, demonstrations, hints, and post-cut diagnoses are support. Automatic assembly is not a mastery score or physical tool proficiency.</p><p><a href="docs/curriculum-content.md" target="_blank">Content Index</a> · <a href="${provenance.source}" target="_blank" rel="noreferrer">Curricular Goals Document</a> · <a href="https://github.com/AbbyUsesAIThatCodes/DesignAndModeling26-27" target="_blank" rel="noreferrer">Class Materials</a></p><p>The game works without private class access. The seven selected targets have been checked against the archived activity pages. A classroom pilot remains pending.</p><button id="records">View Response Records</button>`);$('records').onclick=records}
  function records(){const s=game.session;panel(`<h2>Response Records</h2><p>${s.attempts.filter(a=>a.kind!=='demonstration').length} student cut commitments · ${s.attempts.filter(a=>a.kind==='demonstration').length} demonstrations · ${s.parts.length} automatically placed or kept pieces. These counts measure different things.</p><p>Explanations are marked for teacher review, never automatically passed.</p><pre style="white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px">${escape(JSON.stringify({mode:s.mode,attempts:s.attempts,responses:s.responses},null,2))}</pre><button id="export-records">Save Anonymous Records</button>`);$('export-records').onclick=()=>{const blob=new Blob([JSON.stringify({contentRevision:provenance.revision,mode:s.mode,attempts:s.attempts,responses:s.responses},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MeasureTwice-Anonymous-Responses.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
  function canChange(){game.settle();demoToken++;if(game.session.phase==='inspecting'){panel('<h2>Finish Inspecting First</h2><p>Your committed piece is waiting. Close this panel and choose Keep Piece or Try Again before changing this activity. You can still switch modes and return to it.</p>');return false}return true}
  function chooseLesson(i,practice=false){if(!canChange())return;const s=game.session;s.lesson=i;s.lessonStage=practice?'practice':'guided';s.subdivision=practice?16:lessons[i].scale;s.demonstrating=false;s.hint=false;s.phase='selecting';game.nextSelection();$('panel').close();game.update()}
  function lessonMenu(){panel('<h2>Choose a Lesson</h2><p>Every lesson is available. Return in any order.</p>'+lessons.map((l,i)=>`<button class="lesson-choice" data-lesson="${i}">${l.title}<small style="display:block">${l.objective}</small></button>`).join(''));document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>chooseLesson(Number(b.dataset.lesson)))}
  const status=()=>challengeStatus(game.session,checks,game.house);
  function downloadReport(){try{const text=teacherReport(game.session,checks,game.house,game.manifest,provenance),url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=game.manifest.id+'_Challenge-Report.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){game.emit(error.message)}}
  function checkMenu(){const result=status();panel('<h2>Challenge Progress</h2><p>'+result.correctCount+' of '+checks.length+' Exercises Correct. House: '+(result.houseComplete?'Assembled':'Still to Build')+'.</p><p>Complete every automatic component and the 17-piece house to finish. Written explanations stay for teacher review. First answers, support, and retries are preserved.</p><button id="completion-report" '+(result.complete?'':'disabled')+'>Download Completion Report</button><p>Save the plain text file and attach it to Google Classroom yourself. No account or automatic upload is used.</p><button id="return-house">Build the House</button>'+checks.map((c,i)=>`<button class="lesson-choice" data-check="${i}">${c.id}: ${c.title} — ${result.exercises[i].complete?'Correct':'To Complete'}</button>`).join('')+'<button id="records">View Response Records</button>');$('completion-report').onclick=downloadReport;$('return-house').onclick=()=>{if(!canChange())return;game.session.activity='house';game.session.subdivision=16;game.nextSelection();game.rebuildParts();$('panel').close()};$('records').onclick=records;document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>chooseCheck(Number(b.dataset.check)))}
  function chooseCheck(i){if(!canChange())return;const s=game.session;s.activity='check';s.check=i;s.hint=false;s.subdivision=checks[i].scale;s.phase='selecting';s.readyQuestion=null;game.nextSelection();game.rebuildParts();$('panel').close();if(checks[i].kind==='concept')question(checks[i],false)}
  function retryCheck(){if(!canChange())return;beginRetry(game.session,check().id);chooseCheck(game.session.check)}
  function question(c,willCut){const s=game.session,key=c.id,round=responseRound(s,key),ready=key+':'+round,existing=s.responses.find(r=>r.id===key&&r.round===round);if(existing){if(willCut){s.readyQuestion=ready;game.cut()}else showFeedback(c);return}
    if(c.comparison)game.comparison(c.comparison.actual,c.comparison.needed,false);
    panel(`<h2>${c.title}</h2><p>${c.prompt||c.question}</p><form id="response-form"><fieldset><legend>${c.question||'Your Prediction'}</legend>${c.options.map(o=>`<label><input type="radio" name="answer" value="${escape(o)}" required> ${o}</label>`).join('')}</fieldset>${c.explanation?'<label>Explain Your Reasoning<textarea id="explanation" required placeholder="Your explanation will be kept for teacher review."></textarea></label>':''}<button type="submit">${willCut?'Save Prediction and Cut':'Submit Prediction'}</button></form><p>Feedback appears after your commitment. Keyboard and magnification are access tools, not hints.</p>`);
    $('response-form').onsubmit=e=>{e.preventDefault();const answer=new FormData(e.currentTarget).get('answer'),explanation=c.explanation?$('explanation').value.trim():null;if(c.explanation&&!explanation){$('explanation').setCustomValidity('Write your reasoning before submitting.');$('explanation').reportValidity();return}if(!submitResponse(s,key,answer,c.answer))return;if(c.explanation)submitResponse(s,key+':explanation',explanation,null);if(willCut){s.readyQuestion=ready;$('panel').close();game.cut()}else{game.expose(key);showFeedback(c);game.update()}};
    if(c.explanation)$('explanation').oninput=()=> $('explanation').setCustomValidity('');
  }
  function showFeedback(c){game.expose(c.id);const s=game.session,record=s.responses.filter(r=>r.id===c.id).at(-1);panel(`<h2>Inspect Your Reasoning</h2><p>${record?.correct?'Your selected response matches.':'Compare your response with the explanation.'}</p><p>${c.feedback}</p>${c.explanation?'<p>Your explanation is saved for teacher review. No automatic pass is assigned to typed text.</p>':''}<button id="retry-check">Retry This Exercise</button><button id="next-check">Choose Another Check</button><button id="records">View Response Records</button>`);$('retry-check').onclick=()=>{if(s.mode==='challenge')retryCheck();else{beginRetry(s,c.id);question(c,false)}};$('next-check').onclick=checkMenu;$('records').onclick=records;if(c.comparison)game.comparison(c.comparison.actual,c.comparison.needed,true)}
  function demo(){if(!canChange())return;const s=game.session,l=lesson(),ticket=++demoToken;activeDemo=s;s.demonstrating=true;s.hint=true;exposeLesson(s.lesson);$('panel').close();$('guidance').hidden=false;$('guidance').textContent='Demonstration: '+l.demoText;let i=0;function step(){if(ticket!==demoToken||game.session!==s||s.mode!=='learn'){s.demonstrating=false;return}if(i<l.demo.length){if(l.demoScales)s.subdivision=l.demoScales[i];game.move(Math.max(1,l.demo[i]));game.update();$('guidance').textContent='Demonstration: '+l.demoText;i++;setTimeout(step,$('reduced').checked?0:700)}else{s.demonstrating=false;activeDemo=null;game.move(l.guided);game.update();$('guidance').textContent=l.demoText+' Now make your own guided prediction.';if(l.demoCut){s.demonstrating=true;game.move(l.demoCut);game.cut();s.demonstrating=false}}}step()}
  function practiceQuestion(){const l=lesson(),s=game.session;if(!l.question)return;if(l.id==='MT-L03'&&s.lessonStage==='practice')question({...l,id:l.id+':practice',prompt:'Predict whether 2/8 inch and 1/4 inch coincide.',question:'Do these fractions end together?',options:l.options,answer:l.answer,explanation:true},false);else question({...l,id:l.id+':guided',prompt:l.question,explanation:l.id==='MT-L03'||l.id==='MT-L05'},false)}
  game.setHooks({
    target:s=>s.mode==='free'?s.freeTarget:s.mode==='learn'?(s.lessonStage==='practice'?lessons[s.lesson].practice:lessons[s.lesson].guided):s.activity==='check'?checks[s.check].target:game.house.families[s.family]?.length??null,
    copyCount:s=>s.mode==='challenge'&&s.activity==='check'?checks[s.check].copies??1:1,
    targetLabel:s=>s.mode==='challenge'&&s.activity==='check'?checks[s.check].targetLabel:undefined,
    context:s=>s.mode==='learn'?`${lessons[s.lesson].id}:${s.lessonStage}`:s.mode==='free'?'free':s.activity==='check'?checks[s.check].id:'house:'+game.house.families[s.family]?.id,
    beforeCut:s=>{if(s.mode==='challenge'&&s.activity==='check'){const c=check();if(c.kind==='concept'){question(c,false);return false}if(c.question&&s.readyQuestion!==c.id+':'+responseRound(s,c.id)){question(c,true);return false}}return true},
    inspected:s=>{if(s.mode==='challenge'&&s.activity==='check'){$('result-detail').textContent+=' '+check().feedback;const r=s.responses.filter(r=>r.id===check().id).at(-1);if(r)$('result-detail').textContent+=' Your choice: '+(r.correct?'Correct.':'Try the reasoning again after acknowledging this cut.');game.expose(check().id)}if(s.mode==='learn')exposeLesson(s.lesson)},
    update:s=>{
      if(activeDemo&&activeDemo!==s){activeDemo.demonstrating=false;activeDemo=null;demoToken++}
      $('guidance').hidden=s.mode!=='learn';$('readout').hidden=s.mode==='learn'&&s.lessonStage==='practice';$('checks').textContent='Check Understanding';$('cut-label').hidden=s.phase==='complete';$('target').hidden=s.phase==='complete';
      if(s.mode==='learn'){const l=lesson();if(s.lessonStage!=='practice')exposeLesson(s.lesson);$('order-title').textContent=l.title;$('order-note').textContent=s.lessonStage==='practice'?l.practicePrompt:l.prompt;$('guidance').textContent=l.text;$('guidance').hidden=s.lessonStage==='practice';$('practice').textContent=s.lessonStage==='practice'?'Return to Guided Learning':'Try With Less Help';$('evidence').textContent='Guided and practice responses are separate from Challenge.';$('complete').hidden=true}
      if(s.mode==='challenge'&&s.activity==='check'){const c=check();$('kicker').textContent='Check Understanding';$('order-title').textContent=c.title;$('order-note').textContent=c.prompt;$('target').hidden=c.kind==='concept';$('cut-label').hidden=c.kind==='concept';$('dock').hidden=s.phase!=='selecting'||c.kind==='concept';$('checks').textContent='Choose a Check';$('progress').textContent=`${status().correctCount} of ${checks.length} Exercises Correct`;$('evidence').textContent=hasExposure(s,c.id)?'Previously Viewed · Supported Practice':'First response is recorded before feedback.';if(c.kind==='concept'){$('phase').textContent='Predict Before Feedback';if(!$('answer-question')){const b=document.createElement('button');b.id='answer-question';b.textContent='Answer This Question';$('challenge-controls').prepend(b)}$('answer-question').hidden=false;$('answer-question').onclick=()=>question(c,false)}}
      if($('answer-question')&&!(s.mode==='challenge'&&s.activity==='check'&&check().kind==='concept'))$('answer-question').hidden=true;
      if(s.mode==='challenge'){
        const result=status();
        if(s.activity==='house')$('progress').textContent=`${s.parts.filter(p=>p.family).length} of 17 Pieces · ${result.correctCount}/${checks.length} Exercises`;
        $('complete').hidden=!(result.complete||(s.activity==='house'&&s.phase==='complete'));
        $('complete').textContent=result.complete?'Challenge Complete — Download Your Report From Challenge Progress':'House Assembled — Complete All 30 Exercises to Finish';
        $('checks').textContent='Challenge Progress';
        const retry=$('retry-exercise');retry.hidden=s.activity!=='check';retry.disabled=s.phase!=='selecting'||!hasExposure(s,check().id);
      }else $('retry-exercise').hidden=true;
    }
  });
  $('curriculum').onclick=()=>curriculum();$('practices').onclick=()=>curriculum(game.session.mode==='learn'?lesson():game.session.mode==='challenge'&&game.session.activity==='check'?check():{objective:'Commit an inch measurement, inspect its fit, and build equal-length parts.',goals:['G07','G08','G11','G13'],pages:'A pp. 5, 11–25, 39, 42, 47, 66'});
  $('lessons').onclick=lessonMenu;$('checks').onclick=checkMenu;$('demo').onclick=demo;$('practice').onclick=()=>chooseLesson(game.session.lesson,game.session.lessonStage!=='practice');
  const reasoning=document.createElement('button');reasoning.id='lesson-reasoning';reasoning.textContent='Explain the Idea';$('learning-controls').append(reasoning);reasoning.onclick=()=>{if(lesson().question)practiceQuestion();else {exposeLesson(game.session.lesson);panel(`<h2>${lesson().title}</h2><p>${lesson().feedback}</p>`)}};
  $('hint').onclick=()=>{const s=game.session;s.hint=true;if(s.activity==='check'){game.expose(check().id);exposeLesson(check().lesson)}else game.expose('house:'+game.house.families[s.family]?.id);panel(`<h2>A Measuring Hint</h2><p>${game.session.activity==='check'?lessons[check().lesson].text:'Find the zero graduation. Read whole inches first, then count the fractional spaces.'}</p><p>This response will be recorded as assisted. Later retries remain practice.</p>`)};
  const retry=document.createElement('button');retry.id='retry-exercise';retry.textContent='Retry This Exercise';$('challenge-controls').append(retry);retry.onclick=retryCheck;
  window.mtReview.challengeStatus=status;window.mtReview.retryCheck=retryCheck;window.mtReview.reportText=()=>teacherReport(game.session,checks,game.house,game.manifest,provenance);
  window.mtReview.chooseCheck=chooseCheck;window.mtReview.chooseLesson=chooseLesson;window.mtReview.content=()=>({lessons,checks,provenance});game.update();
  $('panel-content').addEventListener('pointerover',e=>{const d=e.target.closest('details.vocab');if(d)d.open=true});
  $('panel-content').addEventListener('focusin',e=>{const d=e.target.closest('details.vocab');if(d)d.open=true});
}
