import {acceptLessonCut,finishLessonStage,waitingForLessonReasoning} from './lesson-flow.js';
import {lessonGuidance,intervalExplanation} from './intervals.js';
import {lessons,checks,provenance} from './content.js';
import {submitResponse,hasExposure,beginRetry,responseRound,acknowledge} from './model.js';
import {exerciseStatus,challengeStatus,teacherReport} from './assessment.js';
import {currentStep,finishStep,beginRedo,reasoningReady,acknowledgeStep,displayProject} from './construction.js';
export function installLearning(game){
  const {$,panel}=game;let demoToken=0,activeDemo=null;
  const plan=game.construction,step=()=>currentStep(game.session,plan),lesson=()=>lessons[game.session.lesson],check=()=>game.session.mode==='challenge'?checks.find(c=>c.id===step()?.exercise):null;
  const escape=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  const vocab=(word,definition,nested='')=>`<details class="vocab"><summary>${word}</summary><div>${definition}${nested}<p><a href="docs/curriculum-content.md" target="_blank" rel="noreferrer">Open the Reference</a></p></div></details>`;
  function exposeLesson(i){game.expose(lessons[i].id);for(const c of checks.filter(c=>c.lesson===i))game.expose(c.id)}
  function curriculum(entry){for(const c of checks.filter(c=>c.lesson===0||c.lesson===2))game.expose(c.id);panel(`<h2>${entry?'What This Practices':'Curriculum'}</h2><p>${entry?entry.objective||entry.prompt:'Read fractional inches, preserve the whole-inch part, compare equivalent names, and explain how a measured part fits.'}</p><p>${entry?'DM 1.3 '+entry.goals.join(', '):'DM 1.3 G07, G08, G10–G13 and G16'} · ${entry?.pages||lessons[entry?.lesson||0]?.pages}.</p><p>Choose bold vocabulary to keep its explanation open while exploring nested terms.</p>${vocab('Graduation Marks','The lines marking positions on a ruler. Zero is a starting graduation; the physical edge can extend beyond it.',vocab('Interval','The space between two neighboring graduations. Equal intervals represent equal lengths.'))}${vocab('Equivalent Fractions','Different fraction names for the same portion of one whole.',vocab('Unit','The agreed size being counted. Inch, centimetre and millimetre are length units. The chosen instrument names its unit.'))}<p>Cut commitments and separate explanations are evidence. Fixed zero, demonstrations, hints, and post-cut diagnoses are support. Automatic assembly is not a mastery score or physical tool proficiency.</p><p><a href="docs/curriculum-content.md" target="_blank">Content Index</a> · <a href="${provenance.source}" target="_blank" rel="noreferrer">Curricular Goals Document</a> · <a href="https://github.com/AbbyUsesAIThatCodes/DesignAndModeling26-27" target="_blank" rel="noreferrer">Class Materials</a></p><p>The game works without private class access. The seven selected targets have been checked against the archived activity pages. A classroom pilot remains pending.</p><button id="records">View Response Records</button>`);$('records').onclick=records}
  function records(){const s=game.session;panel(`<h2>Response Records</h2><p>${s.attempts.filter(a=>a.kind!=='demonstration').length} student cut commitments · ${s.attempts.filter(a=>a.kind==='demonstration').length} demonstrations · ${s.parts.length} automatically placed or kept pieces. These counts measure different things.</p><p>Legacy current choices are recorded separately from any legacy written explanations. Current activities use choices and measured cuts.</p><pre style="white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px">${escape(JSON.stringify({mode:s.mode,attempts:s.attempts,responses:s.responses},null,2))}</pre><button id="export-records">Save Anonymous Records</button>`);$('export-records').onclick=()=>{const blob=new Blob([JSON.stringify({schemaVersion:2,build:game.manifest,contentRevision:provenance.revision,mode:s.mode,instrument:s.instrument,attempts:s.attempts,responses:s.responses,acknowledgements:s.acknowledgements},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MeasureTwice-Anonymous-Responses.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
  function canChange(){game.settle();demoToken++;if(game.session.phase==='inspecting'){panel('<h2>Finish Inspecting First</h2><p>Your committed piece is waiting. Close this panel and choose Keep Piece or Try Again before changing this activity. You can still switch modes and return to it.</p>');return false}return true}
  function chooseLesson(i,practice=false){if(!canChange())return;const s=game.session;s.lesson=i;s.lessonStage=practice?'practice':'guided';s.subdivision=practice?16:lessons[i].scale;s.demonstrating=false;s.hint=false;s.phase='selecting';game.nextSelection();$('panel').close();game.update()}
  function lessonMenu(){panel('<h2>Choose a Lesson</h2><p>Every lesson is available. Return in any order.</p>'+lessons.map((l,i)=>`<button class="lesson-choice" data-lesson="${i}">${l.title}<small style="display:block">${l.objective}</small></button>`).join(''));document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>chooseLesson(Number(b.dataset.lesson)))}

  const status=()=>challengeStatus(game.session,checks,plan);
  function downloadReport(){try{const text=teacherReport(game.session,checks,plan,game.manifest,provenance),url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=game.manifest.id+'_Challenge-Report.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){game.emit(error.message)}}
  function progress(){const result=status(),s=game.session;
    panel('<h2>Build Progress</h2><p>Chair → Plane → House Exterior. The next part appears automatically after inspection and placement.</p><p>'+result.correctCount+' of 30 Exercises Correct.</p><button id="continue-build">Continue Building</button><button id="completion-report" '+(result.complete?'':'disabled')+'>Download Completion Report</button><p>Save the text file and attach it to Google Classroom yourself. Choices and measured cuts are recorded; independent written reasoning is not assessed.</p>'+plan.projects.map(p=>`<h3>${p.title} — ${result.projects.find(r=>r.id===p.id).complete?'Complete':'In Progress'}</h3><ol>${plan.steps.map((st,i)=>st.project===p.id?`<li>${st.title} — ${s.builtSteps.includes(st.id)?(st.length===null?'Confirmed':'Placed'):i===s.step?'Current':'Coming Later'} ${s.builtSteps.includes(st.id)?`<button data-review="${i}">Review</button>`:''}</li>`:'').join('')}</ol>`).join('')+'<button id="records">View Response Records</button>');
    $('continue-build').onclick=()=> $('panel').close();$('completion-report').onclick=downloadReport;$('records').onclick=records;document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>reviewStep(Number(b.dataset.review)));
  }
  function reviewStep(index){const st=plan.steps[index],s=game.session;if(!s.builtSteps.includes(st?.id))return false;const c=checks.find(c=>c.id===st.exercise),cuts=s.attempts.filter(a=>a.context===st.id);
    panel(`<h2>Review ${st.title}</h2><p>${plan.projects.find(p=>p.id===st.project).title}. ${c?.feedback||'These exact-length members belong to the original house frame.'}</p><p>${cuts.length} cut commitments; ${st.placements.length} placed pieces. Redo keeps the original response history and does not award extra pieces.</p><button id="redo-step">Redo This Step</button><button id="back-progress">Back to Build Progress</button>`);$('redo-step').onclick=()=>redoStep(index);$('back-progress').onclick=progress;return true;
  }
  function redoStep(index){if(!canChange()||!beginRedo(game.session,index,plan))return false;const c=check();beginRetry(game.session,c?.id||step().id);game.nextSelection();game.rebuildParts();$('panel').close();if(step().length===null)question(c,false);return true}
  function question(c,willCut,repair=false){c={...c,explanation:false};const s=game.session,key=c.id,round=responseRound(s,key),ready=key+':'+round,existing=s.responses.find(r=>r.id===key&&r.round===round);
    if(existing){if(willCut){s.readyQuestion=ready;game.cut()}else showFeedback(c,repair);return}
    if(c.comparison&&!repair)game.comparison(c.comparison.actual,c.comparison.needed,false);
    panel(`<h2>${repair?'Review the Plan':c.title}</h2><p>${c.prompt||c.question}</p><form id="response-form"><fieldset><legend>${c.question||'Your Prediction'}</legend>${c.options.map(o=>`<label><input type="radio" name="answer" value="${escape(o)}" required> ${o}</label>`).join('')}</fieldset>${c.explanation?'<label>Explain Your Reasoning<textarea id="explanation" required placeholder="Saved for teacher review, not automatically graded."></textarea></label>':''}<button type="submit">${willCut?'Save Prediction and Cut':'Submit Prediction'}</button></form><p>${repair?'Your correctly measured piece stays in inspection; another cut is not needed.':'Feedback appears after commitment. Keyboard and magnification are access tools, not hints.'}</p>`);
    $('response-form').onsubmit=e=>{e.preventDefault();const answer=new FormData(e.currentTarget).get('answer'),explanation=c.explanation?$('explanation').value.trim():null;if(c.explanation&&!explanation){$('explanation').setCustomValidity('Write your reasoning before submitting.');$('explanation').reportValidity();return}if(!submitResponse(s,key,answer,c.answer))return;if(c.explanation)submitResponse(s,key+':explanation',explanation,null);if(willCut){s.readyQuestion=ready;$('panel').close();game.cut()}else{game.expose(key);if(s.mode==='learn'&&waitingForLessonReasoning(s))continueLesson();else showFeedback(c,repair);game.update()}};
    if(c.explanation)$('explanation').oninput=()=> $('explanation').setCustomValidity('');
  }
  function showFeedback(c,repair=false){const s=game.session;game.expose(c.id);const ready=reasoningReady(s,c),planning=s.mode==='challenge'&&step()?.length===null;
    panel(`<h2>Inspect Your Reasoning</h2><p>${ready?'Your selected response matches.':'Compare your response with the explanation.'}</p><p>${c.feedback}</p>${c.explanation?'<p>Your explanation is saved for teacher review; it has no automatic pass.</p>':''}${ready?`<button id="confirm-plan">${repair?'Return to the Held Piece':planning?'Confirm the Plan':'Continue Learning'}</button>`:'<button id="retry-plan">Try the Reasoning Again</button>'}`);
    if(ready)$('confirm-plan').onclick=()=>{$('panel').close();if(planning&&reasoningReady(s,c)&&s.phase==='selecting'){finishStep(s,plan);game.nextSelection();game.rebuildParts()}else {game.update();if(repair)inspectionCopy(s)}};
    else $('retry-plan').onclick=()=>{beginRetry(s,c.id);question(c,false,repair)};
  }
  function inspectionCopy(s){if(s.mode!=='challenge'||s.phase!=='inspecting')return;const c=check(),ready=reasoningReady(s,c);if(c)$('result-detail').textContent=(s.pending.correct?'The measured length fits. ':'Compare the required and actual spans. ')+c.feedback+(ready?'':' Correct the reasoning before this piece can be placed.');$('ack').textContent=!s.pending.correct?'Try Again':!ready?'Review the Reasoning':s.resumeStep!==null?'Confirm Practice':'Keep Piece'}
  function demo(){if(!canChange())return;const s=game.session,l=lesson(),ticket=++demoToken;activeDemo=s;s.demonstrating=true;s.hint=true;exposeLesson(s.lesson);$('panel').close();$('guidance').hidden=false;$('guidance').textContent='Demonstration: '+(l.id==='MT-L01'?intervalExplanation(l.guided,s.subdivision):l.demoText);let i=0;function step(){if(ticket!==demoToken||game.session!==s||s.mode!=='learn'){s.demonstrating=false;return}if(i<l.demo.length){if(l.demoScales)s.subdivision=l.demoScales[i];game.move(Math.max(1,l.demo[i]));game.update();$('guidance').textContent='Demonstration: '+(l.id==='MT-L01'?intervalExplanation(l.guided,s.subdivision):l.demoText);i++;setTimeout(step,$('reduced').checked?0:700)}else{s.demonstrating=false;activeDemo=null;game.move(l.guided);game.update();$('guidance').textContent=(l.id==='MT-L01'?intervalExplanation(l.guided,s.subdivision):l.demoText)+' Now make your own guided prediction.';if(l.demoCut){s.demonstrating=true;game.move(l.demoCut);game.cut();s.demonstrating=false}}}step()}
  function lessonQuestion(){const l=lesson(),s=game.session;return l.id==='MT-L03'&&s.lessonStage==='practice'?{...l,id:l.id+':practice',prompt:'Predict whether 2/8 inch and 1/4 inch coincide.',question:'Do these fractions end together?',explanation:false}:{...l,id:l.id+':guided',prompt:l.question,feedback:l.id==='MT-L01'?intervalExplanation(s.lessonStage==='practice'?l.practice:l.guided,s.subdivision):l.feedback,explanation:false}}
  function advanceLesson(){const s=game.session;if(!finishLessonStage(s,lessons.length))return;s.subdivision=s.lessonStage==='practice'?16:lesson().scale;s.demonstrating=false;$('panel').close();game.nextSelection();game.emit(s.lessonStage==='complete'?'All five lessons and their practice tasks are complete.':`Next Task: ${lesson().title} - ${s.lessonStage==='practice'?'Try With Less Help':'Guided Learning'}`)}
  function continueLesson(){
    const s=game.session;if(!waitingForLessonReasoning(s))return;const l=lesson();if(!l.question){advanceLesson();return}const c=lessonQuestion(),records=s.responses.filter(r=>r.id===c.id||r.id.startsWith(c.id+':retry-')&&!r.id.endsWith(':explanation')),record=records.at(-1);
    if(record?.correct&&(!c.explanation||s.responses.some(r=>r.id===record.id+':explanation'))){advanceLesson();return}
    if(!record){question(c,false);return}
    panel(`<h2>Inspect Your Reasoning</h2><p>${c.feedback}</p><p>Your original response is saved. Answer the lesson question correctly before the next task; current choices are recorded separately from any legacy written explanations.</p><button id="retry-lesson-reasoning">Try Reasoning Again</button>`);
    $('retry-lesson-reasoning').onclick=()=>question({...c,id:c.id+':retry-'+records.length},false);
  }
  function practiceQuestion(){const l=lesson(),s=game.session;if(!l.question)return;if(l.id==='MT-L03'&&s.lessonStage==='practice')question({...l,id:l.id+':practice',prompt:'Predict whether 2/8 inch and 1/4 inch coincide.',question:'Do these fractions end together?',options:l.options,answer:l.answer,explanation:true},false);else question({...l,id:l.id+':guided',prompt:l.question,explanation:l.id==='MT-L03'||l.id==='MT-L05'},false)}

  game.setHooks({
    complete:s=>s.mode==='learn'&&s.lessonStage==='complete',
    waiting:waitingForLessonReasoning,
    home:s=>s.mode==='challenge'&&displayProject(s,plan)==='plane'?{position:[17,11.5,15],look:[3.35,4,-1.3]}:null,
    target:s=>s.mode==='free'?s.freeTarget:s.mode==='learn'?(s.lessonStage==='practice'?lessons[s.lesson].practice:lessons[s.lesson].guided):currentStep(s,plan)?.length??null,
    copyCount:s=>s.mode==='challenge'?currentStep(s,plan)?.placements.length||1:1,
    targetLabel:s=>s.mode==='challenge'?check()?.targetLabel:undefined,
    context:s=>s.mode==='learn'?`${lessons[s.lesson].id}:${s.lessonStage}`:s.mode==='free'?`free:${s.instrument}:${s.workspace}`:currentStep(s,plan)?.id,
    selecting:s=>{if(s.mode==='challenge'){s.activity='build';s.subdivision=check()?.scale??16;s.readyQuestion=null}},
    isComplete:s=>s.mode==='challenge'&&s.step>=plan.steps.length&&s.resumeStep===null,
    beforeCut:s=>{if(s.phase!=='selecting')return false;if(s.mode==='challenge'){const st=step(),c=check();if(!st)return false;if(st.length===null){question(c,false);return false}if(c?.question&&s.readyQuestion!==c.id+':'+responseRound(s,c.id)){question(c,true);return false}}return true},
    beforeAck:s=>{if(s.mode==='challenge'&&s.phase==='inspecting'&&s.pending.correct&&!reasoningReady(s,check())){const c=check();if(s.responses.some(r=>r.id===c.id&&r.round===responseRound(s,c.id)))beginRetry(s,c.id);question(c,false,true);return false}return true},
    acknowledge:s=>s.mode==='challenge'?acknowledgeStep(s,plan,checks):acknowledge(s,game.house),
    rejected:s=>{if(s.mode==='challenge'&&check()?.question&&!reasoningReady(s,check()))beginRetry(s,check().id)},
    kept:s=>{if(s.mode==='challenge')finishStep(s,plan);else if(acceptLessonCut(s))continueLesson()},
    inspected:s=>{if(s.mode==='challenge'){if(check())game.expose(check().id);inspectionCopy(s)}if(s.mode==='learn')exposeLesson(s.lesson)},
    update:s=>{
      if(activeDemo&&activeDemo!==s){activeDemo.demonstrating=false;activeDemo=null;demoToken++}
      $('guidance').hidden=s.mode!=='learn';$('readout').hidden=s.mode==='learn'&&s.lessonStage==='practice';$('cut-label').hidden=s.phase==='complete';$('target').hidden=s.phase==='complete';$('previous-step').hidden=s.mode!=='challenge';$('plan-order').hidden=true;
      if(s.mode==='learn'){const l=lesson();if(s.lessonStage!=='practice')exposeLesson(s.lesson);$('order-title').textContent=l.title;$('order-note').textContent=s.lessonStage==='practice'?l.practicePrompt:l.prompt;$('guidance').textContent=lessonGuidance(l,s.subdivision);$('guidance').hidden=s.lessonStage==='practice';$('practice').textContent=s.lessonStage==='practice'?'Return to Guided Learning':'Try With Less Help';$('evidence').textContent='Guided and practice responses are separate from Challenge.';$('complete').hidden=true;
        const done=s.lessonStage==='complete';$('demo').hidden=done;$('practice').hidden=done;$('lesson-reasoning').hidden=done;
        if(done){$('order-title').textContent='Lessons Complete';$('order-note').textContent='All five guided lessons and practice tasks are finished. Choose a lesson to review, or open Challenge.';$('guidance').hidden=true;$('target').hidden=true;$('cut-label').hidden=true;$('complete').textContent='Lessons Complete \u00b7 Five Lessons and Their Practice';$('complete').hidden=false;$('phase').textContent='Lessons Complete'}
        else if(waitingForLessonReasoning(s)){$('phase').textContent='Answer the Lesson Question';$('order-note').textContent='Your cut is accepted. Answer the lesson question before the next task.';queueMicrotask(()=>{if(game.session===s&&waitingForLessonReasoning(s)&&!$('panel').open)continueLesson()})}
        else $('phase').textContent='Next Task: '+(s.lessonStage==='practice'?'Try With Less Help':'Guided Learning');
      }
      if(s.mode==='challenge'){
        s.activity='build';const st=step(),c=check(),result=status(),project=plan.projects.find(p=>p.id===st?.project);s.subdivision=c?.scale??16;
        $('kicker').textContent=project?`${project.title} · ${s.resumeStep!==null?'Practice Redo':'Build '+(plan.projects.indexOf(project)+1)+' of 3'}`:'Three Builds Complete';
        $('order-title').textContent=st?.title??'Challenge Complete';$('order-note').textContent=c?.prompt??(st?`Cut ${st.length/16} inches for ${st.placements.length} matching frame members. Confirm inspection before placement.`:'Your chair, plane and house exterior are complete. Download the report from Build Progress.');
        $('progress').textContent=`${result.correctCount} of 30 Exercises Correct`;$('evidence').textContent=`${s.builtSteps.length} of ${plan.steps.length} Build Steps Finished`;
        const shown=displayProject(s,plan);$('object-cue').textContent=shown!==st?.project&&st?`${plan.projects.find(p=>p.id===shown).title} Complete — Next Build: ${project.title}`:'Drag the workshop to inspect the wooden model.';$('checks').textContent='Build Progress';$('previous-step').disabled=!s.builtSteps.length||!['selecting','complete'].includes(s.phase);
        if(result.complete)$('phase').textContent='Three Builds Complete';$('complete').hidden=!result.complete;$('complete').textContent='Challenge Complete — Chair, Plane and House Exterior';
        if(st?.length===null){$('dock').hidden=true;$('target').hidden=true;$('cut-label').hidden=true;$('plan-order').hidden=false;$('phase').textContent='Check the Order Before Cutting'}
        if(s.phase==='inspecting')inspectionCopy(s);
      }
    }
  });
  $('curriculum').onclick=()=>curriculum();$('practices').onclick=()=>curriculum(game.session.mode==='learn'?lesson():check()||{objective:'Measure matching frame members before placing them in the house.',goals:['G07','G08','G11','G13'],pages:'A pp. 5, 11-25, 39, 42, 47, 66'});
  $('lessons').onclick=lessonMenu;$('checks').onclick=progress;$('demo').onclick=demo;$('practice').onclick=()=>chooseLesson(game.session.lesson,game.session.lessonStage!=='practice');
  const reasoning=document.createElement('button');reasoning.id='lesson-reasoning';reasoning.textContent='Explain the Idea';$('learning-controls').append(reasoning);reasoning.onclick=()=>{if(waitingForLessonReasoning(game.session))continueLesson();else if(lesson().question)practiceQuestion();else {exposeLesson(game.session.lesson);panel(`<h2>${lesson().title}</h2><p>${lesson().feedback}</p>`)}};
  $('hint').onclick=()=>{const s=game.session,c=check();s.hint=true;if(c){game.expose(c.id);exposeLesson(c.lesson)}else game.expose(step()?.id);panel(`<h2>A Measuring Hint</h2><p>${c?lessons[c.lesson].text:'Find the zero graduation. Read whole inches first, then count the fractional spaces.'}</p><p>This response and later retries remain supported practice.</p>`)};
  const previous=document.createElement('button');previous.id='previous-step';previous.textContent='Review Previous Step';$('challenge-controls').append(previous);previous.onclick=()=>{const s=game.session,index=Math.min(s.step-1,plan.steps.length-1);reviewStep(Math.max(0,index))};
  const planButton=document.createElement('button');planButton.id='plan-order';planButton.textContent='Check the Order';$('challenge-controls').prepend(planButton);planButton.onclick=()=>question(check(),false);
  window.mtReview.challengeStatus=status;window.mtReview.reviewStep=reviewStep;window.mtReview.redoStep=redoStep;window.mtReview.plan=()=>plan;window.mtReview.reportText=()=>teacherReport(game.session,checks,plan,game.manifest,provenance);
  window.mtReview.chooseLesson=chooseLesson;window.mtReview.content=()=>({lessons,checks,provenance});game.nextSelection();game.rebuildParts();
  $('panel-content').addEventListener('pointerover',e=>{const d=e.target.closest('details.vocab');if(d)d.open=true});
  $('panel-content').addEventListener('focusin',e=>{const d=e.target.closest('details.vocab');if(d)d.open=true});
}
